Repository metasfresh/metasfresh, pull requests merged in 2020-11, with the labels that each got.

#10198 #10035 Can now sort by all types of virtual columns.
  backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/view/descriptor/SqlViewSelectionQueryBuilder.java
Labels: branch:master

#10257 #10238
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Current_Vs_Next_Pricelist_Comparison_Report.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Current_Vs_Next_Pricelist_Comparison_Report_With_PP_PI.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5572420_sys_gh10238AddCurrentVsNextPricelistComparisonFunctions.sql
Labels: branch:intensive_care_uat

#10268 #10267 Added Movement Type Filter To Product Transactions window
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5572830_sys_gh10267AddedMovementTypeFilterToProductTransactionsWindow.sql
Labels: branch:happy_flower_uat

#10306 #10238
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Current_Vs_Next_Pricelist_Comparison_Report.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Current_Vs_Next_Pricelist_Comparison_Report_With_PP_PI.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Current_Vs_Previous_Pricelist_Comparison_Report.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Current_Vs_Previous_Pricelist_Comparison_Report_With_PP_PI.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5573220_sys_gh10238UpdateCurrentVsPreviousAndCurrentVsNextPricelistFunctions.sql
Labels: branch:intensive_care_uat

#10317 creating leadtime column
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5573370_sys_gh10316_leadtime_column.sql
Labels: branch:happy_flower_uat
