Repository metasfresh/metasfresh, pull requests merged in 2020-12, with the labels that each got.

#10347 also filter by product when resolving HUs
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/hu_pporder_issue_producer/CreateDraftIssuesCommand.java
  backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/rest_api/ManufacturingOrderReportProcessCommand.java
  backend/de.metas.manufacturing.rest-api/src/test/java/de/metas/manufacturing/rest_api/ManufacturingOrderAPIServiceTest.java
Labels: type:bug

#10352 Add `outputDirectory` configuration to jaxb2
  backend/de.metas.payment.esr/pom.xml
  backend/de.metas.payment.sepa/schema-pain_001_01_03_ch_02/pom.xml
  backend/de.metas.payment.sepa/schema-pain_008_003_02/pom.xml
  backend/de.metas.printing.common/de.metas.printing.esb.base/pom.xml
  misc/services/camel/de-metas-camel-edi/pom.xml
Labels: type:bug

#10361 gh10357 Add warehouseCode in OLCand
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/PO.java
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/ordercandidates/impl/JsonConverters.java
  backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/ordercandidates/request/JsonOLCandCreateRequest.java
  backend/de.metas.salescandidate.base/src/main/java-gen/de/metas/ordercandidate/model/I_C_OLCand.java
  backend/de.metas.salescandidate.base/src/main/java-gen/de/metas/ordercandidate/model/X_C_OLCand.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCand.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandCreateRequest.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandOrderFactory.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandRepository.java
  backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5574060_sys_gh10357_add_M_Warehouse_ID_in_C_OLCand.sql
  backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/test/resources/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/XmlToOLCandsServiceTest.snap
Labels: branch:happy_flower_uat

#10370 #10279 Update marketing channel ad_ui_elements names.
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5574210_sys_gh10279UpdateMarketingChannelsUiElementName.sql
Labels: branch:master

#10398 Update validation rule to display the correct packing items
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5574360_sys_gh10307_FixPackingInstrunctionForSalesOrderBatchEntry.sql
Labels: branch:master

#10399 #gh10397 added reference to sales order invoice & purchase order invoice, and logic to switch between displaying both https://github.com/metasfresh/metasfresh/issues/10397
  backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5574420_gh10397_ref_commission_invoice_candidate_from_commission_deed.sql
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/references/RelationTypeZoomProvider.java
Labels: branch:master

#10405 Prices of inactive products
  backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java
Labels: branch:intensive_care_uat

#10413 Gh10412
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5574550_sys_gh10412HaddexColumnsToProductTableAndSysConfigsAndErrMsgAndProductWindowAdjustments.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5575090_sys_gh10412AddMessageAndTranslations.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5575110_sys_gh10412_AddSysconfig.sql
  backend/de.metas.business/src/main/java/de/metas/order/model/interceptor/C_OrderLine.java
Labels: branch:master

#10466 10269 fix issues
  frontend/src/actions/InlineTabActions.js
  frontend/src/components/widget/InlineTab.js
  frontend/src/components/widget/InlineTabWrapper.js
  frontend/src/reducers/windowHandler.js
Labels: branch:master
