Repository metasfresh/metasfresh, pull requests merged in 2021-02, with the labels that each got.

#10576 #6697 Lookup anstatt Dropdown bei bestellungen aus Auftrag generieren
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5578000_sys_gh_10575_ChangeLiferanteDropDownIntoSearchFiled.sql
Labels: branch:scary_plum_uat

#10570 change remaining modules from jaxb2-maven-plugin to maven-jaxb2-plugin
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/dataentry/layout/DataEntrySection.java
  backend/de.metas.payment.esr/pom.xml
  backend/de.metas.payment.esr/src/main/xsd/camt.054.001.02/camt.054.001.02.xsd
  backend/de.metas.payment.esr/src/main/xsd/camt.054.001.06/camt.054.001.06.xsd
  backend/de.metas.payment.sepa/schema-pain_001_01_03_ch_02/pom.xml
  backend/de.metas.payment.sepa/schema-pain_008_003_02/pom.xml
  backend/de.metas.printing.common/de.metas.printing.esb.base/pom.xml
  backend/de.metas.shipper.gateway.go/pom.xml
  backend/de.metas.vertical.pharma.msv3.schema.v1/pom.xml
  backend/de.metas.vertical.pharma.msv3.schema.v2/pom.xml
  backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_440_request/pom.xml
  distribution/pom.xml
  misc/dev-support/bootstrap-scripts/mvn_build.sh
  misc/parent-pom/pom.xml
  misc/services/camel/de-metas-camel-edi/pom.xml
  misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/invoicexport/stepcom/StepComXMLInvoicBean.java
  misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/invoicexport/stepcom/StepComXMLInvoicRoute.java
  misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/ordersimport/stepcom/StepComXMLOrdersBean.java
  misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/ordersimport/stepcom/StepComXMLOrdersRoute.java
  misc/services/camel/de-metas-camel-edi/src/main/xsd/stepcom/invoic/Xrech4h.xsd
  misc/services/camel/de-metas-camel-edi/src/main/xsd/stepcom/orders/Xbest4h.xsd
Labels: type:enhancement

#10598 add a fix to display the view C_Printing_Queue_PrintInfo_v in webui
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
Labels: type:bug

#10699 #gh10670 always show DateAcct field on UI, and let it be editable. Propagate via callout changes from DateInvoiced to DateAcct
  backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5580220_sys_gh10670_always_show_dateAcct.sql
  backend/de.metas.business/src/main/java/de/metas/invoice/callout/C_Invoice.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/callout/C_Invoice_Candidate.java
Labels: branch:scary_plum_uat

#10707 #6978 Problembereichscode Liste zur Info bereitstellen
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5580350_sys_gh_10661_RenameProblemCodeValues.sql
Labels: branch:tenacious_d_uat
