Repository metasfresh/metasfresh, pull requests merged in 2022-03, with the labels that each got.

#12609 #gh12607: cant copy product window
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/window/api/impl/ADWindowDAO.java
Labels: branch:master

#12622 #gh12621: add user communication info in user window
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5628620_sys_gh12621_add_communication_info_in_user_window.sql
Labels: branch:tasty_ham_uat

#12649 Updated translations for "Import Format - Subscritions"
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5629580_sys_gh1436_update_translations_import_formats_subcriptions
Labels: branch:master

#12730 Gh12694 pick via recieved quantity in manufacturing order
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5631370_sys_gh12694_add_process_pick_via_recieved_quantity.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/test/java/de/metas/fresh/picking/service/impl/HU2PackingItemsAllocatorTest.java
  backend/de.metas.fresh/de.metas.fresh.base/src/test/java/de/metas/fresh/picking/service/impl/HU2PackingItemsAllocatorTwoSchedsTest.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/PickingCandidateService.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/ProcessHUsAndPickingCandidateCommand.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/picking/service/impl/HU2PackingItemsAllocator.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/picking/service/impl/ShipmentSchedulesSupplier.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Pick.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Pick_ParametersFiller.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewFactory.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_Pick_ReceivedHUs.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/util/HURow.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/util/ProcessPickingRequest.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/util/WEBUI_PP_Order_ProcessHelper.java
Labels: branch:tenacious_d_uat
