Repository metasfresh/metasfresh, pull requests merged in 2022-04, with the labels that each got.

#12754 gh12753_add_bbd_opened_product_window
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5633030_sys_gh12753_add_bbd_opened_product_window.sql
Labels: branch:happy_flower_uat

#12752 #gh12751: add email to SO window / ic window / invoice window / shipments window
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5633010_sys_gh12751_add_email_to_so_ic_i_shipments_windows.sql
Labels: branch:blonde_monkey_uat

#12773 Cause out of memory exception
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/CauseOutOfMemoryError.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5633380_sys_gh12772_add_oome_prozess.sql
Labels: branch:master
