Repository metasfresh/metasfresh, pull requests merged in 2022-06, with the labels that each got.

#13087 gh13086_Adjustment_in_Product_Prices_Window
  backend/de.metas.business/src/main/sql/postgresql/system/43-de.metas.product/5641650_sys_gh13086_Adjustment in_Product_Prices_Window.sql
Labels: branch:inner_silence_uat

#13083 Add Foodadvice Attribute to product
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5641590_sys_gh13082_add_foodadvice_to_product.sql
Labels: branch:science_vessel_uat

#13095 #display project at all HU levels..
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/SqlHUEditorViewRepository.java
Labels: branch:iron_plant_uat

#13121 Master merge iron plant uat fix hu zoomacross
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IReceiptScheduleDAO.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ReceiptScheduleDAO.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/DocumentFilterList.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorViewBuilder.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/HUEditorViewFactoryTemplate.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_ReverseReceipt.java
Labels: branch:master

#13133 #13132 add fr ch as system language & add missing trls
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5642860_sys_gh13132_add_fr_CH_as_Sys_language_and_Trls.sql
Labels: branch:inner_silence_uat

#13134 Master merge inner silence uat add fr ch trls
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5642620_sys_gh13119_receipt_window_adjustment.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5642860_sys_gh13132_add_fr_CH_as_Sys_language_and_Trls.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5641340_sys_gh13071_Purchase_Order_window_adjustments.sql
Labels: branch:master

#13140 Add Filtering by Organisation for Projects
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5642920_sys_gh13138_show_only_projects_in_line_matching_selected_org.sql
Labels: branch:pot_hole_uat

#13155 Gh13153 add firmenbuch nr to business partner window
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner.java
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5643560_sys_add_FirmenbuchNR_to_Business_Partner_Window.sql
Labels: branch:science_vessel_uat

#13159 Gh13158 adjust manufacturing candidate
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Order_Candidate.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Product_Planning.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Order_Candidate.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Product_Planning.java
  backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/service/CreateOrderCandidateCommand.java
  backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5643210_sys_gh13158_Adjust_Manufacturing_candidate.sql
  backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5643230_sys_gh13158_Adjust_Manufacturing_candidate.sql
  backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5643670_sys_gh13158_Adjust_Manufacturing_candidate.sql
Labels: branch:science_vessel_uat

#13163 Master merge science vessel uat
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_BPartner.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Order_Candidate.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Product_Planning.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Order_Candidate.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Product_Planning.java
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5643560_sys_add_FirmenbuchNR_to_Business_Partner_Window.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5643160_sys_gh13145_Food_Advice_Table.sql
  backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/service/CreateOrderCandidateCommand.java
  backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5643210_sys_gh13158_Adjust_Manufacturing_candidate.sql
  backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5643230_sys_gh13158_Adjust_Manufacturing_candidate.sql
  backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5643670_sys_gh13158_Adjust_Manufacturing_candidate.sql
Labels: branch:master

#13168 Master merge science vessel followup 1
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_BPartner.java
  backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5643780_sys_gh13158_Adjust_Manufacturing_candidate.sql
Labels: branch:master

#13185 gh13183 Rename Sektion to Organisation
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5644240_sys_gh13183_rename_element_sektion_to_organisation.sql
Labels: branch:hostile_tractor_uat

#13186 Master merge hostile tractor uat rename sektion organisation
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5644240_sys_gh13183_rename_element_sektion_to_organisation.sql
Labels: branch:master

#13194 #12825 flag m_tour_id as calculated
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5644620_sys_gh12825_flag_m_tour_id_as_claculated.sql
Labels: branch:science_vessel_uat

#13196 Master merge science vessel uat branch
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5644620_sys_gh12825_flag_m_tour_id_as_claculated.sql
Labels: branch:master

#13225 Master merge pot hole uat filter project based on organisation
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5645280_sys_gh13138_Show_only_Projects_Organisation.sql
Labels: branch:master
