Repository metasfresh/metasfresh, pull requests merged in 2022-11, with the labels that each got.

#13873 Add unique index on AD_Window(AD_Element_ID)
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5663030_sys_AD_Window_AD_Element_ID_unique_index.sql
Labels: branch:master

#13936 mobile UI: Barcode text input: debounce
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5664360_sysconfig_barcodeScanner_inputText_debounceMillis.sql
  misc/services/mobile-webui/mobile-webui-frontend/src/components/BarcodeScannerComponent.jsx
  misc/services/mobile-webui/mobile-webui-frontend/src/reducers/settings.js
Labels: patch_mgmt

#13938 AD_Column.assertColumnNameValid: allow CreatedBy, UpdatedBy exceptional ID column names
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/column/model/interceptor/AD_Column.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/api/impl/ADTableDAO.java
Labels: patch_mgmt

#13956 Master adorable badger gh13923
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/InvoiceLineAllocId.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
  backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5663950_sys_gh13921_OpenInvoicesForCandidate_AD_Message.sql
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/decorator/DraftInvoiceDecorator.java
  frontend/src/components/header/Breadcrumb.js
Labels: branch:master

#13964 when extending C_Flatrate_Term, ignore terms that are already extended
  backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/process/C_Flatrate_Term_Extend_And_Notify_User.java
Labels: patch_mgmt

#13973 fix problem with a workaround when the actual problem is not there
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5637700_sys_C_Incoterm_Trl_ID_default_value.sql
Labels: branch:inner_silence_uat, patch_mgmt

#13985 the sha1 below doesn't always work with our migration tool;
  backend/de-metas-salesorder/src/main/sql/postgresql/system/70-de-metas-salesorder/5611419_sys_gh11947_fix_sql_folder_names.sql
  backend/de-metas-salesorder/src/main/sql/postgresql/system/70-de-metas-salesorder/5611420_sys_gh11947_entity_de_metas_salesorder.sql
  backend/de-metas-salesorder/src/main/sql/postgresql/system/70-de-metas-salesorder/5611430_sys_gh11947_wp_CompleteShipAndInvoiceWorkpackageProcessor.sql
  backend/de-metas-salesorder/src/main/sql/postgresql/system/70-de-metas-salesorder/5612270_sys_gh11947_wp_ProcessOLCandsWorkpackageProcessor.sql
Labels: patch_mgmt

#14001 `Tenacious_d_uat` To `master` merge gh13992
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/sequence/impl/DocumentNoBuilder.java
Labels: branch:master

#14003 Fix NPE that happens if IExportProcessor.process throws an exception
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/TranslatableStringBuilder.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/process/rpl/ExportProcessor2Wrapper.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/exceptions/ReplicationException.java
Labels: patch_mgmt

#14014 Configure webui frontend Quantity/Amount/CostPrice/Number default precision via `webui.frontend.widget.Quantity.defaultPrecision` sysconfig
  backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5666110_sysconfig_webui_frontend_Quantity_defaultPrecision.sql
  frontend/src/actions/AppActions.js
  frontend/src/utils/tableHelpers.js
Labels: branch:adorable_badger_uat
