Repository metasfresh/metasfresh, pull requests merged in 2022-05, with the labels that each got.

#12955 prototype that might fix the issue
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/mm/attributes/AttributeSetInstanceId.java
  backend/de.metas.business/src/main/java/de/metas/order/OrderFactory.java
  backend/de.metas.business/src/main/java/de/metas/order/OrderLineBuilder.java
  backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/PurchaseCandidate.java
  backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/localorder/PurchaseOrderFromItemFactory.java
  backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/remotepurchaseitem/PurchaseItemRepository.java
  backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/remotepurchaseitem/PurchaseOrderItem.java
Labels: branch:mad_orange_uat

#12963 fixing failing tests
  backend/de.metas.purchasecandidate.base/src/test/java/de/metas/purchasecandidate/PurchaseCandidateTestTool.java
  backend/de.metas.purchasecandidate.base/src/test/java/de/metas/purchasecandidate/purchaseordercreation/localorder/PurchaseOrderFromItemFactoryTest.java
  backend/de.metas.purchasecandidate.base/src/test/java/de/metas/purchasecandidate/purchaseordercreation/localorder/PurchaseOrderFromItemsAggregatorTest.java
Labels: branch:mad_orange_uat

#12954 Gh12953 invoicing support aggregating different values where possible
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/BPartnerContactId.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/BPartnerInfo.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/location/DocumentLocation.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5636290_sys_gh12849_IC_Agg_No_Contact.sql
  backend/de.metas.business/src/main/java/de/metas/invoice/location/adapter/InvoiceDocumentLocationAdapter.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationEngine.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImplBuilder.java
Labels: branch:intensive_care_uat

#13004 Disable changelog for Processed and DocAction columns of M_InOut
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5639380_sys_gh12994_remove_not_needed_changelogs_from_m_inout.sql
Labels: branch:scary_plum_uat

#13023 add ol-handler
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inout/invoicecandidate/M_InOutLine_HandlerTest.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/spi/impl/C_OrderLine_Handler_Test.java
Labels: branch:iron_plant_uat

#13044 Fix disabled unit tests
  backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/generatedcomponents/ComponentGeneratorContext.java
  backend/de.metas.manufacturing/src/test/java/de/metas/manufacturing/generatedcomponents/CopyAttributesFromBOMLineGeneratorTest.java
  backend/de.metas.manufacturing/src/test/java/de/metas/manufacturing/generatedcomponents/MacAddressGeneratorTest.java
  backend/de.metas.manufacturing/src/test/java/de/metas/material/planning/pporder/impl/PPOrderBOMBLTest.java
  backend/de.metas.manufacturing/src/test/java/org/eevolution/api/impl/CreatePPOrderCostsCommandTest.java
  backend/de.metas.manufacturing/src/test/java/org/eevolution/api/impl/PPOrderCostsTestHelper.java
  backend/de.metas.manufacturing/src/test/java/org/eevolution/api/impl/ProductLowLevelCalculatorTest.java
  backend/de.metas.manufacturing/src/test/java/org/eevolution/costing/OrderBOMCostCalculatorRepositoryTest.java
  backend/de.metas.manufacturing/src/test/java/org/eevolution/event/PPOrderRequestedEventHandlerTests.java
  backend/de.metas.material/dispo-service/src/test/java/de/metas/material/dispo/service/event/handler/ForecastCreatedHandlerTest.java
  backend/de.metas.material/dispo-service/src/test/java/de/metas/material/dispo/service/event/handler/pporder/PPOrderCreatedHandlerTests.java
  backend/de.metas.payment.esr/src/main/java/de/metas/payment/spi/impl/QRCodeStringParser.java
  backend/de.metas.payment.esr/src/test/java/de/metas/payment/esr/QRCodePaymentTest.java
  backend/de.metas.payment.esr/src/test/java/de/metas/payment/spi/impl/QRCodeStringParserTest.java
Labels: branch:master

#13050 Window: Handling Unit
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5640530_sys_gh13037_add_project_hu_window.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5640850_sys_gh13037_add_project_hu_reltype.sql
  backend/de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU.java
  backend/de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/X_M_HU.java
Labels: branch:iron_plant_uat
