Repository metasfresh/metasfresh, pull requests merged in 2022-08, with the labels that each got.

#13381 gh13380 skip the copy of windows translations , because the name_ad_language unique index on window_trl will be broken
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/window/api/impl/ADWindowDAO.java
Labels: branch:adorable_badger_uat

#13377 Partial Payment Invoicing
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Incoterms.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Incoterms.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5648520_sys_gh13368_ispartialpayment_invoice_candidate.sql
  backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_C_Invoice_Candidate.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
Labels: branch:inner_silence_uat

#13387 Tests and Error messages for QR IBAN Sepa Export
  backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
  backend/de.metas.payment.sepa/base/src/main/sql/postgresql/system/70-de.metas.payment.sepa/5648860_sys_gh13384_SEPA_Export_Err_Invalid_Reference.sql
  backend/de.metas.payment.sepa/base/src/test/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02_Test.java
Labels: branch:mad_orange_uat

#13393 rewritten from sales invoice to purchase invoice
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5648520_sys_gh13368_ispartialpayment_invoice_candidate.sql
  backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_C_Invoice_Candidate.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
Labels: branch:master, branch:inner_silence_uat

#13401 Make akonto flag readonly
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5649600_sys_gh17_akontoflag_readonly.sql
Labels: branch:master, branch:inner_silence_uat

#13434 New Section Code window
  backend/de.metas.acct.base/src/main/java/de/metas/acct/gljournal/IGLJournalLineDAO.java
  backend/de.metas.acct.base/src/main/java/de/metas/acct/gljournal/impl/GLJournalLineDAO.java
  backend/de.metas.acct.base/src/main/java/de/metas/acct/interceptor/GL_JournalLine.java
  backend/de.metas.acct.base/src/main/java/de/metas/acct/model/validator/GL_Journal.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_GL_Journal.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_GL_Journal.java
  backend/de.metas.business/src/main/java/de/metas/invoice/interceptor/C_InvoiceLine.java
  backend/de.metas.business/src/main/java/de/metas/shipment/model/interceptor/M_InOutLine.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/reservation/interceptor/C_OrderLine.java
Labels: branch:adorable_badger_uat
