Repository metasfresh/metasfresh, pull requests merged in 2022-07, with the labels that each got.

#13324 Merge adorable badger uat into master
  backend/de.metas.business/src/main/sql/postgresql/ddl/functions/SetBaseLanguage.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647430_sys_gh13302_add_process_change_base_language.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647510_sys_gh13302_add_process_change_base_language.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647580_sys_gh13302_add_process_change_base_language.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647680_sys_gh13302_add_process_change_base_language.sql
Labels: branch:master

#13343 renamed the sql migrationscript to .sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5629580_sys_gh1436_update_translations_import_formats_subcriptions.sql
Labels: branch:master

#13345 HOTFIX Accounting Transactions sidelist Reference for documents missing again
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/references/related_documents/fact_acct/FactAcctRelatedDocumentsProvider.java
Labels: branch:science_vessel_uat

#13349 gh13302 restrict process to system only
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5648330_sys_gh13302_add_process_change_base_language.sql
Labels: branch:master, branch:adorable_badger_uat

#13359 Master merge inner silence uat gh13339
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_CostRevaluation.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_CostRevaluationLine.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_DocType.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_CostRevaluation.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_CostRevaluationLine.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/ui/spi/ITabCallout.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/ui/spi/TabCalloutAdapter.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5647970_sys_gh13323_Prefinancing_FlatrateConditions.sql
  backend/de.metas.business/src/main/java/de/metas/costrevaluation/CostRevaluationDocumentHandler.java
  backend/de.metas.business/src/main/java/de/metas/costrevaluation/CostRevaluationDocumentHandlerProvider.java
  backend/de.metas.business/src/main/java/de/metas/costrevaluation/CostRevaluationRepository.java
  backend/de.metas.business/src/main/java/de/metas/costrevaluation/callout/M_CostRevaluation.java
  backend/de.metas.business/src/main/java/de/metas/costrevaluation/impl/CostRevaluationId.java
  backend/de.metas.business/src/main/java/de/metas/costrevaluation/impl/CostRevaluationLineId.java
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647750_sys_gh13319_final_product_price.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647770_sys_gh13319_final_product_price.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647840_sys_gh13319_final_product_price.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647850_sys_gh13319_final_product_price.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5648110_sys_gh13319_final_product_price.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5648300_sys_gh13319_final_product_price.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5648340_sys_gh13319_final_product_price.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/test/java/de/metas/util/lang/All_RepoIdAware_Classes_Test.java
Labels: branch:master

#13362 gh13337 fixes business partner bank account filters
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5648460_sys_gh13337_Adjustment_Payment_and_BankStatement_Windows.sql
Labels: branch:scary_plum_uat
