Repository metasfresh/metasfresh, pull requests merged in 2022-12, with the labels that each got.

#14065 Flat Rate Term extension uses wrong Bill Partner
  backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Flatrate_Term.java
Labels: patch_mgmt

#14070 Mi adorable badger uat delivery planning UI fixes
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5666940_sys_gh13942_delivery_planning_ui_fixes.sql
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
Labels: branch:master

#14088 Don't fail if there are no cost details on Activity Control posting
  backend/de.metas.acct.base/src/main/java/de/metas/acct/doc/AcctDocRequiredServicesFacade.java
  backend/de.metas.business/src/main/java/de/metas/costing/ICostingService.java
  backend/de.metas.business/src/main/java/de/metas/costing/impl/CostingService.java
  backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/acct/DocLine_CostCollector.java
  backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/acct/Doc_PPCostCollector.java
Labels: patch_mgmt

#14085 added translations to delivery planning
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5667020_sys_gh13942_added_delivery_planning_translations.sql
Labels: branch:mad_orange_uat

#14100 relocate and rename sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647676_sys_gh13846_Fix_trl_NL_duplicates_test.sql
Labels: branch:master

#14102 trls duplicate fix Fr_CH
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647677_sys_gh13846_Fix_trl_fr_CH_duplicates.sql
Labels: branch:master

#14106 Update 5647677_sys_gh13846_Fix_trl_fr_CH_duplicates.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647677_sys_gh13846_Fix_trl_fr_CH_duplicates.sql
Labels: branch:master

#14118 fix after_migration
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5667990_sys_gh14117_fix_after_migration.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5668140_sys_gh14117_fix_after_migration_2.sql
Labels: patch_mgmt

#14110 Sub-Task No 5: Test & Fix Sales order (w/ ship ) - Product Planning - Distribution
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5666950_sys_gh14105_DD_Order_DatePromised_Date_Time.sql
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/M_Locator_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/distribution/DD_NetworkDistributionLine_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/distribution/DD_NetworkDistributionLine_StepDefData.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/distribution/DD_NetworkDistribution_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/distribution/DD_NetworkDistribution_StepDefData.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/distributionorder/DD_OrderLine_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/distributionorder/DD_OrderLine_StepDefData.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/distributionorder/DD_Order_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/distributionorder/DD_Order_StepDefData.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/inventory/M_Inventory_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/material/cockpit/MD_Cockpit_DDOrder_Detail_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/material/cockpit/MD_Cockpit_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/material/dispo/MD_Candidate_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/material/dispo/MD_Candidate_StepDefTable.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/material/dispo/MD_Candidate_StepDefTableTransformer.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/productplanning/PP_Product_Planning_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipper/M_Shipper_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/transaction/M_Transaction_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/warehouse/M_Warehouse_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/workflow/AD_Workflow_StepDefData.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/delivery/deliveryRules.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/inventory.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/supplyRequiredQtyViaDistribution.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/supplyRequiredQtyViaPurchase.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/shipmentSchedule/shipmentScheduleExport.feature
  backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddorder/lowlevel/interceptor/DD_Order_PostMaterialEvent.java
  backend/de.metas.material/dispo-commons/src/main/java/de/metas/material/dispo/commons/RequestMaterialOrderService.java
  backend/de.metas.material/dispo-commons/src/test/java/de/metas/material/dispo/commons/CandidateServiceTests.java
  backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/handler/TransactionEventHandler.java
  backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/handler/ddorder/DDOrderAdvisedOrCreatedHandler.java
  backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/handler/ddorder/DDOrderCreatedHandler.java
Labels: patch_mgmt

#14150 Fixing the script for FR and NL trls fix
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647674_sys_gh13846_Fix_trl_NL_FR_duplicates_test.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647676_sys_gh13846_Fix_trl_NL_duplicates_test.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647677_sys_gh13846_Fix_trl_fr_CH_duplicates.sql
Labels: branch:master

#14154 HandlingUnitsService.toJsonHUAttributes: make sure JsonHUAttribute.code is set
  backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/HandlingUnitsService.java
Labels: patch_mgmt

#14188 update infrastructure db dockerfile
  misc/dev-support/docker/infrastructure/db/Dockerfile
Labels: patch_mgmt
