Repository metasfresh/metasfresh, pull requests merged in 2022-02, with the labels that each got.

#12458 ExternalSystem_Other_ConfigParameter add description column
  backend/de.metas.externalsystem/src/main/sql/postgresql/system/80-de.metas.externalsystem/5624080_sys_gh12457_ExternalSystem_Other_ConfigParameter_description_column.sql
Labels: branch:mad_orange_uat

#12456 #gh1345 : Make sure that M_Replenish LevelMax is >= LevelMin
  backend/de.metas.business/src/main/java/de/metas/material/replenish/interceptors/M_Replenish.java
Labels: branch:master

#12491 gh12490:Activate RelType with isTableRecordIDTarget = Y
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5624920_sys_gh12490_Activate_RelType_with_isTableRecordIDTarget_Y.sql
Labels: branch:master

#12519 #12518 Copy incoterm location from order to invoice and location
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutInOut.java
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInOut.java
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoice.java
  backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/invoicecandidate/HandlerTools.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/returns/ReturnsInOutHeaderFiller.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/spi/impl/InOutProducerFromShipmentScheduleWithHU.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_C_Invoice_Candidate.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceHeader.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationEngine.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImpl.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceHeaderImplBuilder.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java
  backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5625580_gh12518_Add_IncotermLocationIntoInvoiceCandidate.sql
  backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5625780_sys_gh12518_AddIncotermsIntoAggregation.sql
Labels: branch:tasty_ham_uat

#12557 #gh12550: Order entry default delivery address and contact is not set
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
Labels: branch:tasty_ham_uat

#12592 gh12590:Products Proposal button should not be present under Order Tab
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5627190_sys_gh12590_remove_product_proposal_from_tax_tab.sql
Labels: branch:master
