Repository metasfresh/metasfresh, pull requests merged in 2023-10, with the labels that each got.

#16351 fix MKTG_Platform so that a platform with org_id=0 can be used on any org
  backend/de.metas.marketing/base/src/main/sql/postgresql/system/90-de.metas.marketing.base/5705220_sys_fix_mktg_platform_logic.sql
Labels: branch:hard_encoded_uat

#16326 attempt to fix the rightclick-popup-menu
  backend/de.metas.adempiere.adempiere/client/src/main/java/org/compiere/grid/ed/menu/EditorContextPopupMenu.java
Labels: ops:without_review_approval

#16432 metas ts/master/trivial change
  .mergify.yml
  .testspace.yml
Labels: ops:without_review_approval

#16526 Use DateAcct as parameter and adjust functions and report Costs Per Date
  backend/de.metas.acct.base/src/main/sql/postgresql/ddl/functions/getCostsPerDate.sql
  backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5708280_sys_Add_getcost_per_date.sql
  backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5708430_sys_AddReport_Costs_per_date.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/reports/productcosts/report.jrxml
Labels: branch:intensive_care_uat
