Repository metasfresh/metasfresh, pull requests merged in 2023-03, with the labels that each got.

#14767 fix the bug that MF demands on a country-id
  backend/de.metas.business/src/main/java/de/metas/pricing/IEditablePricingContext.java
  backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/project/service/commands/CreateQuotationFromProjectCommand.java
  backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/project/service/commands/createQuotationFromProjectCommand/ProjectQuotationPricingInfo.java
Labels: patch_mgmt

#14797 fix message when reversing
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5680730_sys_gh631_updated_reverse_msg.sql
Labels: branch:tenacious_d_uat

#14822 fix selection
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5681400_sys_gh14721_ImportBPartnerBlockStatus.sql
Labels: ops:without_review_approval

#14855 ci(Mergify): configuration update
  .mergify.yml
Labels: ops:without_review_approval

#14913 fixed npe
  backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
Labels: branch:hard_encoded_uat

#14917 cherry pick npe fix
  backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
Labels: branch:intensive_care_uat

#14937 port cucumber fixes for commission-scenarios
  backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Flatrate_Term.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/hierarchyCommissionAndLicenseFeeCommissionContracts.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/tradeMarginCommissionContract.feature
  misc/dev-support/idea-runConfigurations/Run SQL Migrations - iron_plant_uat.run.xml
Labels: ops:without_review_approval

#14942 merge hard_encoded_uat => master
  backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
Labels: ops:without_review_approval

#14938 fix PrintingDataTest (depended on previous tests)
  backend/de.metas.printing/de.metas.printing.base/src/test/java/de/metas/printing/api/impl/PrintingDataTest.java
Labels: ops:without_review_approval

#14989 Master merge scary plum uat
  misc/dev-support/docker/infrastructure/.idea/misc.xml
  misc/dev-support/docker/infrastructure/.idea/modules.xml
  misc/dev-support/docker/infrastructure/.idea/runConfigurations.xml
  misc/dev-support/docker/infrastructure/.idea/vcs.xml
Labels: ops:without_review_approval
