Repository metasfresh/metasfresh, pull requests merged in 2023-07, with the labels that each got.

#15786 Fix "SpringApplicationContext not configured yet"
  backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
Labels: ops:without_review_approval

#15792 Port - fix unit test that failed if not certain other tests were executed first
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/AbstractNewAggregationEngineTests.java
Labels: ops:dont_auto_create_PR

#15812 Fix migration SQL problem
  backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5693660_sys_ModCntr_Log_Mandatory_changes.sql
Labels: ops:without_review_approval

#15804 ShipmentScheduleFromSubscriptionOrderLineVetoer: fix veto logic
  backend/de.metas.contracts/src/main/java/de/metas/contracts/inoutcandidate/ShipmentScheduleFromSubscriptionOrderLineVetoer.java
Labels: patch_mgmt

#15903 Master inner silence uat merge 07182023
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5695840_sys_gh15897_drop_C_Year_ID_from_C_Order.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5694520_sys_gh16205_add_extension_not_allowed_list_value.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5694830_sys_gh16205_add_process_extend_flatrate_conditions.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5694840_cli_gh16205_add_unique_index_on_modCntr_settings.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5695070_sys_gh16205_add_extension_not_alloawed_message.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5695340_sys_gh16205_filter_years_by_settings_calendar.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5695450_sys_gh16205_rename_process_and_fix_trls.sql
  backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_C_Flatrate_Conditions.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateBL.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/process/C_Flatrate_Conditions_ModularContract_Clone.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/SubscriptionTermEventListener.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Flatrate_Conditions.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettingsDAO.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettingsQuery.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/controller/WindowRestController.java
  frontend/src/api/window.js
Labels: ops:without_review_approval

#15960 Master inner silence uat 07272023 dm ps
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Order.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_DocType.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Order.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Order.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Order.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/DocBaseType.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/IDocTypeBL.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/impl/DocTypeBL.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseBL.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5696540_sys_gh15907_C_Order_calendar_and_year.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5696630_sys_gh15907_C_Order_filter_columns.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5696840_sys_gh15907_C_Order_SO_Modular_Log_relType.sql
  backend/de.metas.business/src/main/java/org/eevolution/api/PPOrderDocBaseType.java
  backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/I_ModCntr_Settings.java
  backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_ModCntr_Settings.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/FlatrateTermRequest/ModularFlatrateTermRequest.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateBL.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/impl/PurchaseOrderLineModularContractHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/impl/SalesOrderLineModularContractHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/interceptor/C_OrderLine.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/log/ModularContractLogDAO.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettingsDAO.java
  backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5696530_sys_gh_ModCntr_Settings_IsSOTrx_column.sql
  backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5696560_sys_gh15907_ad_message_SalesOrderLineModularContractHandler.sql
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_OrderLine_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Order_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/StepDefAction.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/billofmaterial/PP_Product_Bom_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_Log_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pporder/PP_Order_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleLogInventory.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleLogPurchaseOrder.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleLogSalesOrder.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/modular/issueReceipt.feature
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/modular/ModularPPOrderService.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/modular/impl/PPOrderQtyModularContractHandler.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/modular/interceptor/PP_Order.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/modular/interceptor/PP_Order_Qty.java
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5696490_sys_gh15943_PP_Order_ModularFlatrateTerm.sql
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5696600_sys_gh15943_ModularOrderDocType.sql
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5696810_sys_gh15943_ModularFlatrateTermColumn_mandatoryLogic.sql
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5697000_sys_gh15943_ModularFlatrateTerm_AD_Messages.sql
  backend/de.metas.manufacturing/src/main/java/org/eevolution/api/IPPOrderBL.java
  backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderBL.java
  backend/de.metas.manufacturing/src/main/java/org/eevolution/model/MPPOrder.java
  backend/de.metas.material/planning/src/main/java/de/metas/material/planning/pporder/LiberoException.java
Labels: ops:merge_towards_master
