Repository metasfresh/metasfresh, pull requests merged in 2023-09, with the labels that each got.

#16134 Add Open Sans Fonts
  backend/de.metas.report/metasfresh-report-service/pom.xml
Labels: ops:without_review_approval

#16156 hotfix: on webui login make sure we are using logged user language
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/notification/UserNotificationsService.java
Labels: patch_mgmt

#16166 Remove need to set obsolete auth-token in env
  misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/CoreConstants.java
  misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/v2/BudgetProjectRouteBuilder.java
  misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/v2/WorkOrderProjectRouteBuilder.java
Labels: ops:without_review_approval

#16213 Master inner silence uat merge 09152023
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/invgroup/interceptor/ModCntrInvoicingGroupRepository.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/TableRecordReference_StepDefUtil.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_InvoicingGroup_Product_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_InvoicingGroup_Product_StepDefData.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_InvoicingGroup_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_InvoicingGroup_StepDefData.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/interiminvoice/invoice/C_BPartner_InterimContract_GenerateInterimInvoice_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate/C_Invoice_Candidate_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipment/M_InOut_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/interim/modularInterimContract.feature
Labels: ops:without_review_approval, ops:merge_towards_master

#16221 fix migration scripts which failed when running on vanilla-DB *in order*
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5603820_sys_gh11709_CostEstimateDocument.sql
Labels: ops:without_review_approval

#16275 Creating Cucumber Tests for shipping notification (`M_Shipping_Notification`, `M_Shipping_NotificationLines`)
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Order_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shippingNotification/M_Shipping_NotificationLine_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shippingNotification/M_Shipping_NotificationLine_StepDefData.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shippingNotification/M_Shipping_Notification_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shippingNotification/M_Shipping_Notification_StepDefData.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/shippingNotification/shippingNotification.feature
Labels: ops:dont_auto_merge

#16295 cherry pick changes to fix undefined when calling getIncludedTabTopActions
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/controller/WindowRestController.java
  frontend/src/api/window.js
Labels: patch_mgmt

#16289 fix unit tests
  backend/de.metas.contracts/src/test/java/de/metas/contracts/order/ContractOrderTest.java
Labels: ops:without_review_approval

#16297 Manually port unit test fix from master
  backend/de.metas.contracts/src/test/java/de/metas/contracts/impl/AbstractFlatrateTermTest.java
  backend/de.metas.contracts/src/test/java/de/metas/contracts/impl/ContractChangeBLTest.java
  backend/de.metas.contracts/src/test/java/de/metas/contracts/order/ContractOrderTest.java
Labels: ops:without_review_approval

#16304 Inner silence/uat/fix x2go swingui
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/plaf/AdempierePLAF.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/AdempiereComboBoxUI.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/AdempiereEditorPaneUI.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/AdempiereLabelUI.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/AdempiereScrollPaneUI.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/AdempiereSplitPaneUI.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/AdempiereTabbedPaneUI.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/AdempiereToolBarUI.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/MetasFreshScrollBarUI.java
  backend/de.metas.adempiere.adempiere/client/src/main/java-legacy/org/compiere/apps/AEnv.java
  backend/de.metas.adempiere.adempiere/client/src/main/java-legacy/org/compiere/apps/APanel.java
Labels: ops:without_review_approval

#16301 Metas marcus/merge/from/iron plant uat
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/plaf/AdempierePLAF.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/AdempiereComboBoxUI.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/AdempiereEditorPaneUI.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/AdempiereLabelUI.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/AdempiereScrollPaneUI.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/AdempiereSplitPaneUI.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/AdempiereTabbedPaneUI.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/AdempiereToolBarUI.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/plaf/MetasFreshScrollBarUI.java
  backend/de.metas.adempiere.adempiere/client/src/main/java-legacy/org/compiere/apps/AEnv.java
  backend/de.metas.adempiere.adempiere/client/src/main/java-legacy/org/compiere/apps/APanel.java
Labels: ops:without_review_approval
