Repository metasfresh/metasfresh, pull requests merged in 2023-08, with the labels that each got.

#15997 Remove AD_TreeNode from view C_Element_levels
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/C_Element_Levels.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/75-de.metas.fresh.reports/5697870_sys_gh15996_C_Element_Levels_without_treenodes.sql
Labels: ops:without_review_approval

#16015 inner_silence/uat/fix_contractModuleLogPurchaseOrder_feature
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/impl/InventoryLineModularContractHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/impl/PurchaseOrderLineModularContractHandler.java
Labels: ops:without_review_approval

#16014 Master merge soft panda uat 03082023
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5689040_fix_C_OLCand_virtual_columns.sql
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/edi/EDI_Desadv_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/edi/desadvAndInvoic.feature
  backend/de.metas.edi/src/main/java/de/metas/edi/api/IDesadvDAO.java
  backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvBL.java
  backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvDAO.java
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5697950_sys_desadv_set_processed_flag_for_dont_send.sql
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5697990_sys_desadv_matching_improvement.sql
  backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/functions/get_db_columns_sqlvalues.sql
  backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5689180_get_db_columns_sqlvalues.sql
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/edi_desadv/ChangeEDI_ExportStatusHelper.java
  misc/dev-support/docker/infrastructure/scripts/21_drop_db_template.sh
Labels: ops:without_review_approval

#16049 duplicate key in headeraggregation
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationDAO.java
Labels: patch_mgmt

#16055 Tweak migration-scripts for a legacy-DB
  backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5616940_sys_gh12089_Adding_nutritional_data_product_window.sql
  backend/de.metas.async/src/main/sql/postgresql/system/42-de.metas.async/5624386_sys_gh12591_recreate_c_queue_overview_v.sql
  backend/de.metas.async/src/main/sql/postgresql/system/42-de.metas.async/5624388_sys_gh12591_recreate_c_queue_archived_overview_v.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5609590_sys_gh11866_InvoiceRule_AfterPick.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5615520_sys_gh12069_addMarketPlaceWindowAndCustomColumns2Product.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5616450_sys_gh12069_addFIFields2ProductWindow.sql
  backend/metasfresh-dist/base/src/main/sql/postgresql/system_archived/90-de.metas.endcustomer.mf15/5463250_cli_gh1609_basic_setup_production.sql
Labels: ops:without_review_approval

#16068 fix further SQL migration issues that can happen on long-running instances
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5609590_sys_gh11866_InvoiceRule_AfterPick.sql
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5697950_sys_desadv_set_processed_flag_for_dont_send.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5606340_sys_cleanup_x_mrp_tables_and_related_process.sql
Labels: ops:without_review_approval

#16069 SW - direct shipment and invoice
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/order/processor/ProcessOLCandProcessor.java
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow/70_JsonOLCandProcessRequest.json
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/happyFlow_zeroTax/70_JsonOLCandProcessRequest.json
Labels: ops:without_review_approval

#16079 Fix migration-scripts that caused trouble on certain instances
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5646045_sys_gh13480_Duplicate_TRL_Corrections_From_AD_Element.sql
  backend/de.metas.dunning/src/main/sql/postgresql/system/50-de.metas.dunning/5654830_sys_gh13558_dunningCandidate_onlyUpdate.sql
Labels: ops:without_review_approval

#16086 propagate simulation dates to `WOTargetStartDate` and `WOTargetEndDat…
  backend/de.metas.business/src/main/java/de/metas/project/workorder/step/WOProjectStepRepository.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/project/workorder/export/workOrderProjectDataExportAudit.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/project/workorder/workOrderProjectAPI.feature
Labels: ops:without_review_approval, ops:merge_towards_master

#16087 Master iron plant uat merge 08232023
  backend/de.metas.business/src/main/java/de/metas/project/workorder/step/WOProjectStepRepository.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/project/workorder/export/workOrderProjectDataExportAudit.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/project/workorder/workOrderProjectAPI.feature
Labels: ops:without_review_approval, ops:merge_towards_master

#16089 Master inner silence uat merge 08232023
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/util/lang/impl/TableRecordReferenceSet.java
  backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_ModCntr_Log.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/IFlatrateBL.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/IModularContractTypeHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/impl/SalesInvoiceLineModularContractHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/impl/SalesOrderLineModularContractHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/impl/ShipmentLineModularContractHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/interceptor/C_Invoice.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/log/LogEntryDocumentType.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/log/ModularContractLogDAO.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/log/ModularContractLogQuery.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettings.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettingsDAO.java
  backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5699380_sys_gh16063_ad_message_SalesInvoiceLineModularContractHandler.sql
  backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5699500_sys_gh16063_AD_RelationType_ModCntr_Log_C_Invoice_SO.sql
  backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5699540_sys_gh16063_extend_AD_Ref_List_ModCntr_Log_DocumentType.sql
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_Log_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleLogSalesInvoice.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/contractModuleLogShipment.feature
Labels: ops:without_review_approval, ops:merge_towards_master

#16103 skip validation for endDate when startDate is provided (#16101)
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/project/workorder/WorkOrderProjectStepRestService.java
  backend/de.metas.business/src/main/java/de/metas/project/workorder/step/WOProjectStep.java
  backend/de.metas.business/src/main/java/de/metas/project/workorder/step/WOProjectStepRepository.java
Labels: ops:without_review_approval, ops:merge_towards_master

#16104 Master iron plant uat merge 08252023
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/project/workorder/WorkOrderProjectStepRestService.java
  backend/de.metas.business/src/main/java/de/metas/project/workorder/step/WOProjectStep.java
  backend/de.metas.business/src/main/java/de/metas/project/workorder/step/WOProjectStepRepository.java
Labels: ops:without_review_approval, ops:merge_towards_master

#16114 cloning workflow fix starting node + cucumbers
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/service/impl/AD_WF_Node_POCopyRecordSupport.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/service/impl/AD_Workflow_POCopyRecordSupport.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/service/impl/ClonedWFNodesInfo.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/wrapper/IInterfaceWrapperHelper.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/GeneralCopyRecordSupport.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/InterfaceWrapperHelper.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/workflow/AD_Workflow_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/workflow/workflow.feature
Labels: ops:dont_auto_merge

#16096 Master merge from magic oak uat
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/service/impl/AD_WF_Node_CopyRecordSupport.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/service/impl/AD_WF_Node_CopyTemplateCustomizer.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/service/impl/AD_Workflow_CopyRecordSupport.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/service/impl/AD_Workflow_CopyTemplateCustomizer.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/workflow/service/impl/ClonedWFNodesInfo.java
  backend/de.metas.business/src/main/java/org/adempiere/model/CopyValidator.java
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5698890_gh16028_extend_field_length_for_name_and_value_on_ad_workflow_and_ad_wf_node_tables.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5700100_sys_gh16088_configure_ad_wf_node_name_and_value_to_direct_copy_cloning_strategy.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5700190_sys_gh16088_configure_ad_workflow_name_to_make_unique_cloning_strategy.sql
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/workflow/AD_Workflow_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/workflow/PP_WF_Node_Product_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/workflow/workflow.feature
Labels: ops:dont_auto_merge

#15986 intensive_care/uat/minor_pom_improvements
  backend/de.metas.contracts/pom.xml
  backend/de.metas.dunning/pom.xml
  backend/de.metas.printing.rest-api-impl/pom.xml
  backend/de.metas.printing/de.metas.printing.base/pom.xml
  backend/de.metas.shipper.gateway.commons/pom.xml
Labels: ops:without_review_approval

#16122 Modular contract logs for manufacturing: Positive/negative quantity for receipt/issue (resp.)
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/modular/issueReceipt.feature
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/modular/impl/PPCostCollectorModularContractHandler.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/modular/interceptor/PP_Cost_Collector.java
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5700330_gh_16116_update_and_add_ad_message_for_issue_and_receipt_of_production_order.sql
Labels: ops:dont_auto_merge
