Repository metasfresh/metasfresh, pull requests merged in 2023-04, with the labels that each got.

#15062 When generating import format template make sure the right file extension and charset is used
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/DataImportService.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/format/ImpFormat.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/format/ImpFormatType.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/impexp/parser/csv/FlexImpDataLineParser.java
  backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/impexp/format/ImpFormatTest.java
  backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/impexp/format/ImpFormatTypeTest.java
Labels: patch_mgmt

#15072 Master iron plant uat merge 04052023
  backend/de.metas.business/src/main/java/de/metas/project/workorder/stepresource/WOProjectStepResourceService.java
  backend/de.metas.business/src/test/java/de/metas/project/workorder/calendar/WOProjectCalendarServiceTest.java
  backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/functions/isNumeric.sql
  backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5683072_sys_gh168_create_isNumeric_function.sql
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/project/step/ResolveReservationViewFactory.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/project/step/process/C_Project_WO_Step_ResolveReservationView_Launcher.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/descriptor/RelatedProcessDescriptorUtil.java
Labels: ops:without_review_approval, ops:merge_towards_master

#15156 Adorable badger uat change review request body
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/invoice/review/JsonInvoiceReviewService.java
  backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/v2/invoice/JsonInvoiceReviewUpsertItem.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_Review_StepDef.java
Labels: ops:without_review_approval

#15173 Do not create HU Trace for top HU in advance
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/trace/HUTraceEventsService.java
Labels: patch_mgmt

#15182 #15163 display IncotermLocation in PO window too
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5686100_sys_gh15163_fix_incoterm_location_translation.sql
Labels: branch:release

#15186 minor improvements
  .mergify.yml
  .testspace.yml
  backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/bpartner/service/impl/BPartnerBL_RetrieveContactOrNullTests.java
  misc/dev-support/docker/infrastructure/scripts/99_down.sh
  misc/dev-support/maven/settings.xml
Labels: ops:without_review_approval

#15205 Metas ts/master merge mad orange uat
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_Fact_Acct_Transactions_View.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_Fact_Acct_Transactions_View.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/exceptions/AdempiereException.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/exceptions/DBException.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/currency/Amount.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/Language.java
  backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/lang/SOTrxTest.java
  backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/impexp/BankStatementImportTableSqlUpdater.java
  backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositeCachingKeysMapper.java
  backend/de.metas.business/src/main/java/de/metas/payment/api/impl/PaymentBL.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Order_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/docType/C_DocType_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/hu/M_HU_CreateReceipt_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipment/M_InOut_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bpartner/blockBPartner.feature
  backend/de.metas.material/planning/src/test/java/de/metas/material/planning/pporder/impl/PPOrderBOMBL_computeQtyToIssueBasedOnFinishedGoodReceipt_more_Test.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/accounting/process/Fact_Acct_OpenLinkedFacts_ProcessHelper.java
  backend/pom.xml
Labels: ops:without_review_approval, ops:dont_auto_create_PR
