Repository metasfresh/metasfresh, pull requests merged in 2023-06, with the labels that each got.

#15442 Deactivate the moving average cost element
  backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5689960_sys_gh15414_deactivate_avg_rolling_costElement.sql
Labels: ops:without_review_approval, ops:dont_auto_create_PR

#15461 Update affected M_ShipmentSchedules after stock change
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Order_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/RESTUtil.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/docOutbound/orderDocOutbound.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoiceRules.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoicecandidate/packingmaterial/shipments.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/shipmentSchedule/shipmentSchedule.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/shipmentSchedule/shipmentScheduleExport.feature
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/candidate/commands/ProcessHUsAndPickingCandidateCommand.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/segments/ShipmentScheduleSegmentFromHUAttribute.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleUpdater.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/spi/ShipmentScheduleStockChangedEventHandler.java
Labels: ops:without_review_approval

#15469 Update shipment schedules also when DeliveryDate_Override is changed
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/shipmentSchedule/shipmentSchedule.feature
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/modelvalidator/M_ShipmentSchedule.java
Labels: ops:without_review_approval, ops:dont_auto_create_PR

#15470 Fix SQL syntax error when building whereclause
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/tree/spi/impl/MenuTreeSupport.java
Labels: ops:without_review_approval, ops:dont_auto_create_PR

#15483 #15452 prevent changing UOM of a used product
  backend/de.metas.business/src/main/java/de/metas/product/IProductDAO.java
  backend/de.metas.business/src/main/java/de/metas/product/impl/ProductDAO.java
  backend/de.metas.business/src/main/java/de/metas/product/model/interceptor/M_Product.java
  backend/de.metas.business/src/main/sql/postgresql/system/43-de.metas.product/5690420_sys_gh15452_add_product_used_message.sql
Labels: patch_mgmt

#15505 fix tax code translation
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5690570_sys_gh15471_fix_tax_code_translation.sql
Labels: branch:inner_silence_uat

#15515 improve dev-env
  misc/dev-support/docker/infrastructure/scripts/95_start.sh
  misc/dev-support/docker/infrastructure/scripts/97_stop.sh
  misc/dev-support/idea-runConfigurations/Run SQL Migrations - release.run.xml
  misc/dev-support/idea-runConfigurations/RunCucumberTest - release.run.xml
Labels: ops:dont_auto_create_PR

#15498 attempt to fix failing cucumber build
  .github/workflows/cicd.yaml
Labels: ops:without_review_approval, ops:dont_auto_create_PR

#15514 Fix ClassCastException if picking process is called from HU editor
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Pick.java
  misc/dev-support/docker/infrastructure/scripts/93_status.sh
Labels: ops:without_review_approval

#15544 Start distributing tests a bit
  .github/workflows/cicd.yaml
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/accounting.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/apiaudit/apiAuditDELETE.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/availableForSales.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bpartner/createBPartnerV1.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/createProductionOrder.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/groupInvoiceCandidates.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceCandidateOverrideFields.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceCandidateQtyToInvoiceOverride.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoiceCandidatesAggrgation.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoicecandidate/packingmaterial/receipts.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoicecandidate/packingmaterial/shipments.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/supplyRequiredQtyViaDistribution.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/zRunLatest/zRunLastestInvoiceCandidatesHeaderAggregationKey.feature
Labels: ops:without_review_approval, ops:dont_auto_create_PR

#15571 Improve MD_Cockpit_StepDef error-msg
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/material/cockpit/MD_Cockpit_StepDef.java
Labels: ops:without_review_approval

#15582 Minor improvements to make the code around UnreturnedConnectionTimeoutMillis clearer
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/db/DB_PostgreSQL.java
Labels: ops:without_review_approval

#15634 Fix field inventory line field names
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5692170_sys_fix_two_invetory_line_fields.sql
Labels: ops:without_review_approval

#15650 Add modified_carbon_uatand zulu_alpha to mergify and testspace
  .mergify.yml
  .testspace.yml
Labels: ops:without_review_approval, ops:dont_auto_create_PR

#15644 Start distributing tests a bit - also on release
  .github/workflows/cicd.yaml
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/apiaudit/apiAuditDELETE.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bpartner/createBPartnerV1.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/createProductionOrder.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceCandidateOverrideFields.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceCandidateQtyToInvoiceOverride.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoicecandidate/packingmaterial/receipts.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoicecandidate/packingmaterial/shipments.feature
Labels: ops:without_review_approval, ops:dont_auto_create_PR

#15655 workaround for a db deadlog during migration
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5661990_sys_gh_add_sales_fields_to_partner.sql
  misc/dev-support/docker/infrastructure/env-files/modified_carbon_uat.env
  misc/dev-support/idea-runConfigurations/Run SQL Migrations - modified_carbon_uat.run.xml
  misc/dev-support/idea-runConfigurations/RunCucumberTest - modified_carbon_uat.run.xml
Labels: ops:without_review_approval

#15654 Fix some sequences' maxvalue
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5692580_sys_quickfix_sequences.sql
Labels: patch_mgmt, ops:without_review_approval, ops:dont_auto_create_PR

#15717 minor - remove duplicated script
  misc/dev-support/docker/infrastructure/scripts/21_drop_db_template.sh
  misc/dev-support/docker/infrastructure/scripts/21_drop_template.sh
Labels: ops:without_review_approval, ops:dont_auto_create_PR

#15738 Fix flaky unit test TestTwoShipmentsOneInvoicePriceOverrideZero
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/AbstractNewAggregationEngineTests.java
Labels: patch_mgmt, ops:without_review_approval

#15743 Metas ts/release/merge from/master
  backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningRepository.java
  backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/DeliveryPlanningService.java
  backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/interceptor/M_Delivery_Planning.java
  backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/interceptor/M_ShipperTransportation.java
  backend/de.metas.deliveryplanning.base/src/main/java/de/metas/deliveryplanning/invoicecandidate/DeliveryPlanningICHandlerExtension.java
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5693510_sys_gh15670_string_agg_with_distinct_EDIDesadvDocumentNo_column.sql
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/OrderLineHandlerExtension.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/AbstractNewAggregationEngineTests.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/spi/impl/C_OrderLine_Handler_Test.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/spi/impl/QtyDeliveredFromOrderToInvoiceTest.java
Labels: ops:dont_auto_create_PR

#15762 Metas ts/intensive care uat/mergefrom/intensive care hotfix
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Campaign_Price.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Campaign_Price.java
  backend/de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPrice.java
  backend/de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPriceRepository.java
  backend/de.metas.business/src/main/java/de/metas/pricing/rules/campaign_price/CampaignPricingRule.java
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5690560_sys_gh15481_CampaignPrice_PriceList.sql
Labels: ops:dont_auto_create_PR

#15780 metas-ts/release/merge-from/master
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5646045_sys_gh13480_Duplicate_TRL_Corrections_From_AD_Element.sql
Labels: ops:dont_auto_create_PR
