Repository metasfresh/metasfresh, pull requests merged in 2023-02, with the labels that each got.

#14543 when importing products, prevent summing up qties for different products
  backend/de.metas.handlingunits.base/src/main/java/de/metas/inventory/impexp/InventoryImportProcess.java
Labels: patch_mgmt

#14565 #14552 C_Invoice_OverrideDueDate allow only single selection, reword error message to reflect that, add process to quickactions
  backend/de.metas.business/src/main/java/de/metas/invoice/process/C_Invoice_OverrideDueDate.java
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5677020_sys_gh14552_add_to_quickActions_reword_error_msg.sql
Labels: branch:adorable_badger_uat

#14642 Fix NPE when the non-mandatory M_HU.M_Locator_ID is <= 0
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUShipmentAssignmentBL.java
Labels: patch_mgmt

#14519 NOTFIX NPE on OrderBL.getLocationEmail(orderId)
  backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
Labels: patch_mgmt

#14495 make sure that HUs are removed from sourceHU when draft-issued
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/pporder/api/impl/hu_pporder_issue_producer/CreateDraftIssuesCommand.java
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5675270_sys_gh14493_cleanup_M_Source_HU.sql
Labels: patch_mgmt, ops:without_review_approval

#14648 Create diagnostic view for c_queue_workpackage
  backend/de.metas.async/src/main/sql/postgresql/ddl/view/de.metas.async/C_Queue_Processing_Stats_V.sql
  backend/de.metas.async/src/main/sql/postgresql/system/42-de.metas.async/5678180_sys_gh14647_create_view_c_queue_processing_stats_v.sql
Labels: patch_mgmt, ops:without_review_approval

#14693 don't restore snapshot if service repair
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/IHUInOutBL.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/impl/HUInOutBL.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inout/returns/ReturnsServiceFacade.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/M_InOut.java
Labels: patch_mgmt

#14705 Gh12478 api call fix (#14695)
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/model/QueryHelper.java
Labels: branch:master
