Repository metasfresh/metasfresh, pull requests merged in 2023-01, with the labels that each got.

#14253 webui quick input: try submitting on Enter key even if is not the last field (part 2)
  frontend/src/__tests__/components/table/TableQuickInput.test.js
  frontend/src/__tests__/reducers/WidgetHandler.test.js
  frontend/src/__tests__/reducers/tableQuickInputHandler.test.js
  frontend/src/actions/GenericActions.js
  frontend/src/actions/IndependentWidgetsActions.js
  frontend/src/actions/TableQuickInputActions.js
  frontend/src/api/window.js
  frontend/src/api/windowQuickInput.js
  frontend/src/components/table/TableFilter.js
  frontend/src/components/table/TableQuickInput.js
  frontend/src/components/widget/List/List.js
  frontend/src/components/widget/List/RawList.js
  frontend/src/components/widget/RawWidget.js
  frontend/src/constants/ActionTypes.js
  frontend/src/constants/actions/TableQuickInputActionTypes.js
  frontend/src/constants/actions/WindowActions.js
  frontend/src/containers/WidgetWrapper.js
  frontend/src/reducers/index.js
  frontend/src/reducers/tableQuickInputHandler.js
  frontend/src/reducers/widgetHandler.js
  frontend/test_setup/fixtures/independent_widgets/reducers.json
  frontend/test_setup/fixtures/table/table_quickinput.json
Labels: patch_mgmt

#14094 de_DE and de_CH trls fixes for AD_Menu
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5667160_sys_gh13846_fix_trls_AD_Menu.sql
Labels: branch:release

#14293 extra trls that needed to be reapplied
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5667170_sys_gh13846_extra_trls_reapply.sql
Labels: branch:release

#14309 #14257 add AD_Org_ID field to External References window
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/invoicecandidates/impl/CreateInvoiceCandidatesService.java
  backend/de.metas.externalreference/src/main/sql/postgresql/system/80-de.metas.externalreference/5671110_sys_gh14257_add_orgId_to_ExternalReferences_window.sql
Labels: patch_mgmt

#14343 some more missing trls (#14313)
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5671150_sys_gh13846_more_missing_trls.sql
Labels: branch:master

#14366 POInfoColumn.ValueMin, ValueMax: trim blank to null
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/POInfoColumn.java
Labels: patch_mgmt

#14380 Fix HUReceiptScheduleBL by not collecting the HUs of inactive RSAs
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/IHUReceiptScheduleDAO.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/HUReceiptScheduleBL.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/HUReceiptScheduleDAO.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/HUReceiptScheduleListener.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/HUReceiptScheduleWeightNetAdjuster.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/model/validator/M_ReceiptSchedule.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/spi/impl/InOutProducerFromReceiptScheduleHU.java
  backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/allocation/transfer/HUTransformServiceReceiptCandidatesTests.java
  backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/receiptschedule/impl/ReceiptScheduleHUAllocationsTest.java
Labels: ops:without_review_approval

#14374 Port "Find & update en_US window names in de menu, 5.175 release"
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5667160_sys_gh13846_fix_trls_AD_Menu.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5667170_sys_gh13846_extra_trls_reapply.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5671150_sys_gh13846_more_missing_trls.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5671240_sys_gh13846_missing_de_CH_trls.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5671840_sys_gh13846_missing_de_trls.sql
Labels: ops:without_review_approval

#14445 Modernize JsonInvoicePaymentCreateRequest where deserialization failed
  misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/invoice/JsonInvoicePaymentCreateRequest.java
  misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/invoice/JsonPaymentAllocationLine.java
  misc/de-metas-common/de-metas-common-rest_api/src/test/java/de/metas/common/rest_api/v2/invoice/JsonInvoicePaymentCreateRequestTest.java
Labels: patch_mgmt, ops:without_review_approval

#14465 updated taxcode column
  backend/de.metas.datev/src/main/sql/postgresql/ddl/views/RV_DATEV_Export_Fact_Acct_Invoice.sql
  backend/de.metas.datev/src/main/sql/postgresql/ddl/views/RV_DATEV_Export_Fact_Acct_Invoice_All.sql
  backend/de.metas.datev/src/main/sql/postgresql/ddl/views/RV_DATEV_Export_Fact_Acct_Invoice_PerTax.sql
  backend/de.metas.datev/src/main/sql/postgresql/system/5674410_sys_accounting_export_views.sql
  backend/de.metas.datev/src/main/sql/postgresql/system/5674420_sys_vatcode_column_added.sql
Labels: branch:science_vessel_uat

#14468 fix SQL behavior on legacy DBs
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5615520_sys_gh12069_addMarketPlaceWindowAndCustomColumns2Product.sql
Labels: ops:without_review_approval
