Repository metasfresh/metasfresh, pull requests merged in 2023-11, with the labels that each got.

#16612 Product proposal: post-integration re-namings
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsLoader.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/service/OrderProductProposalsService.java
Labels: branch:intensive_care_uat

#16626 Fix externalsystems printing bug
  misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/v2/PrintingRouteBuilder.java
Labels: ops:without_review_approval

#16700 Merge to master from origin/tenacious_d_uat
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5603820_sys_gh11709_CostEstimateDocument.sql
Labels: ops:dont_auto_merge

#16730 webui frontend: when calling a top action correctly send selected row ids
  frontend/src/components/table/TableFilter.js
Labels: patch_mgmt

#16776 merge intensive_care_hotfix to intensive_care_uat
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/invoice/InvoiceId.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/JavaProcess.java
  backend/de.metas.business/src/main/java/de/metas/bpartner/product/stats/BPartnerProductStatsRepository.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/stock/mdStock_AddInventory.feature
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsData.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsLoader.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/process/WEBUI_BPartner_ProductsProposal_Launcher.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/process/WEBUI_Order_ProductsProposal_Launcher.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/process/WEBUI_ProductsProposal_Launcher_Template.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/view/BPartnerProductsProposalViewFactory.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalViewFactoryTemplate.java
Labels: ops:dont_auto_merge

#16794 Fix not working cache invalidation on source column changed
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/POInfo.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/model/ColumnSqlCacheInvalidateRequestFactories.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/model/ColumnSqlCacheInvalidateRequestInitializer.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/api/ColumnSqlSourceDescriptor.java
Labels: patch_mgmt

#16789 DocumentCollection: on cache invalidate don't remove Document from cache if it's new and not already saved
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5708740_sys_gh16545_Index_Table.sql
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/DocumentCollection.java
Labels: patch_mgmt
