Repository metasfresh/metasfresh, pull requests merged in 2023-05, with the labels that each got.

#15215 div improvements
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/M_Product_StepDefData.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/StepDefData.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/apiauditfilter/API_Request_Audit_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/commission/hierarchy/C_CommissionSettingsLine_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/commission/hierarchy/C_HierarchyCommissionSettings_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_InvoiceLine_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/product/M_Product_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_ExportAudit_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_QtyPicked_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/accounting.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/approvedforinvoice/approvedForInvoice.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/automateOrderCand/automateOrderCandToOrderAndShipmentAndInvoice.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/availableForSales.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bankStatement/camt53Import.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bpartner/export/bpartnerExport.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/hierarchyCommissionAndLicenseFeeCommissionContracts.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/mediatedCommissionContract.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/tradeMarginCommissionContract.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/compensationGroup.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/callorder/callOrderContract.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/createInvoiceCandidate.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/edi/desadvAndInvoic.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/edi/ediDesadvPack.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/edi/ediExport.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/groupInvoiceCandidates.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/interim/partialInvoicing.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceAPI.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceCandidateOverrideFields.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceCandidateQtyToInvoiceOverride.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoiceCandidatesAggrgation.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoiceReview.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoiceRules.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoicecandidate/invoiceCandidate.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/manualPrice/createPurchaseCandidateManualPrice.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/manualPrice/manualPriceOLCandToInvoice.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/supplyRequiredQtyViaDistribution.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/paymentRules.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/pporder/exportPPOrderLeichMehl.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/project/budget/export/budgetProjectExport.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/project/workorder/export/workOrderProjectExport.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/renderInvoiceAddress.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/serviceIssue/budgetIssueEffortControl.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/serviceIssue/effortControlGenerateInvoiceCandidate.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/serviceIssue/effortControlPurchaseInvoiceCandidate.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/serviceIssue/effortIssueEffortControl.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/serviceIssue/syncActivityAndLabel.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/simulation/purchaseSimulation.feature
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationEngine.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateHandlerBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/approvedforinvoice/finders/impl/OrderDependentFinder.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/accounting/process/Fact_Acct_OpenLinkedFacts_ProcessHelper.java
  backend/de.metas.util.web/src/main/java/de/metas/util/web/audit/ApiAuditService.java
Labels: ops:without_review_approval, ops:dont_auto_create_PR

#15220 Fix failing cucumbers
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/hierarchyCommissionAndLicenseFeeCommissionContracts.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/tradeMarginCommissionContract.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/shipment/emptiesReceive.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/shipment/emptiesReturn.feature
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
Labels: ops:dont_auto_create_PR

#15252 Fix remaining test problems
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoicecandidates/impl/CreateInvoiceCandidatesService.java
  backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/invoicecandidates/impl/JsonInsertInvoiceCandidateServiceTest.java
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrder.java
  backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/IPaymentTermRepository.java
  backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/impl/PaymentTermQuery.java
  backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/impl/PaymentTermRepository.java
  backend/de.metas.contracts/src/test/java/de/metas/contracts/impl/FlatrateTermDataFactory.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/CucumberLifeCycleSupport.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_Review_StepDef.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateHandlerBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/ExternallyReferencedCandidate.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/ExternallyReferencedCandidateRepository.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/NewManualInvoiceCandidate.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inout/invoicecandidate/M_InOutLine_HandlerTest.java
Labels: ops:without_review_approval, ops:dont_auto_create_PR

#15301 Doc_PPCostCollector: create Fact_Acct records even if cost is zero, because we want to have the Qty recorded too; post only accountable cost elements; avoid cost details multiple times
  backend/de.metas.business/src/main/java/de/metas/costing/AggregatedCostAmount.java
  backend/de.metas.manufacturing/src/main/java/de/metas/costing/methods/ManufacturingAveragePOCostingMethodHandler.java
  backend/de.metas.manufacturing/src/main/java/de/metas/costing/methods/ManufacturingStandardCostingMethodHandler.java
  backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/acct/Doc_PPCostCollector.java
Labels: patch_mgmt

#15306 Fix the REST-API method to PUT
  misc/services/camel/de-metas-camel-externalsystems/core/src/main/java/de/metas/camel/externalsystems/core/to_mf/v2/WorkOrderProjectRouteBuilder.java
Labels: ops:without_review_approval

#15326 minor improvements
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/ordercandidates/impl/MasterdataProvider.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandRepository.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
Labels: ops:without_review_approval

#15335 Metas ts/master/merge from/mad orange uat
  backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/async/C_PurchaseCandidates_GeneratePurchaseOrders.java
  backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/localorder/PurchaseOrderAggregationKey.java
  misc/services/admin/buildfile.groovy
  misc/services/camel/de-metas-camel-edi/buildfile.groovy
  misc/services/camel/de-metas-camel-externalsystems/buildfile.groovy
  misc/services/procurement-webui/nginx/buildfile.groovy
  misc/services/procurement-webui/procurement-webui-backend/buildfile.groovy
  misc/services/procurement-webui/procurement-webui-frontend/buildfile.groovy
  misc/services/procurement-webui/rabbitmq/buildfile.groovy
Labels: ops:dont_auto_create_PR

#15328 use OrgId from PurchaseCandidate instead of user's OrgId when processing purchase candidates into orders
  backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/remoteorder/RealVendorGatewayInvoker.java
  backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/remoteorder/VendorGatewayInvokerFactory.java
Labels: patch_mgmt

#15388 remove dwControl font
  backend/de.metas.report/metasfresh-report-service/pom.xml
Labels: ops:without_review_approval

#15386 update-docker-compose.yml
  misc/dev-support/docker/infrastructure/docker-compose.yml
Labels: patch_mgmt

#15406 Don't try to update M_Product.LowLevel when copying PP_Product_BOMLines (because it's guaranteed that the new BOMLine is at the same level as an existing PP_Product_BOMLine)
  backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Product_BOMLine.java
Labels: patch_mgmt

#15434 manually port fix for deliveryRules.feature from commit 7ee03b0889fde…
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/hu/M_HU_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/delivery/deliveryRules.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/shipment/reversedShipment.feature
Labels: ops:without_review_approval, ops:dont_auto_create_PR
