Repository metasfresh/metasfresh, pull requests merged in 2024-08, with the labels that each got.

#18596 Fix js builds (mobileUI and procurementUI)
  misc/services/mobile-webui/mobile-webui-frontend/package.json
  misc/services/procurement-webui/procurement-webui-frontend/package.json
Labels: ops:without_review_approval, ops:auto_merge

#18599 Merge to master from origin/vampire_textbook_uat
  backend/de.metas.edi/src/main/sql/postgresql/ddl/views/edi_cctop_140_v_view.sql
  backend/de.metas.edi/src/main/sql/postgresql/ddl/views/edi_cctop_901_991_v_view.sql
  backend/de.metas.edi/src/main/sql/postgresql/ddl/views/edi_cctop_invoic_500_v_view.sql
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5730520_sys_gh18532_invoic_include_pmtDiscount_as_surchargeAmt_DDL.sql
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5730780_sys_gh18532_further_extend_INVOIC_export.sql
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5730900_sys_gh18532_further_extend_INVOIC_views_DDL.sql
  misc/de-metas-common/de-metas-common-product/src/main/java/de/metas/common/product/v2/request/constants/SwaggerDocConstants.java
  misc/services/camel/de-metas-camel-edi/src/main/xsd/metasfresh/schema.xsd
Labels: porting-branch

#18225 Merge to master from origin/soft_panda_uat
  backend/de.metas.business/src/main/java/de/metas/pricing/service/PriceListsCollection.java
  backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5726916_sys_gh18259_activatePOReference_InDesadvExport.sql
Labels: porting-branch

#18674 Fix camt payment matching by using equals instead of ILIKE %invoiceDocOrEsrRefNoCandidate%
  backend/de.metas.banking/de.metas.banking.camt53/src/main/java/de/metas/banking/camt53/BankStatementCamt53Service.java
Labels: patch_mgmt

#18681 Fix ViewExcelExporter in case of column not displayed because of displayLogic
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/exceptions/AdempiereException.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/view/ViewExcelExporter.java
Labels: patch_mgmt, ops:auto_merge

#18687 merging after rollout pink_rooster_uat_7 into pink_rooster_hotfix
  .github/workflows/cicd.yaml
  docker-builds/cucumber/run.cmd
  docker-builds/cucumber/stop.cmd
  docker-builds/health/containerHealthCheck.sh
Labels: branch:master

#18699 Merge to intensive_care_uat from origin/intensive_care_hotfix
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrder.java
  backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java
  backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5731470_sys_gh_Delete_2_legacy_Callouts.sql
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/callout/OrderPricingSystem.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/callout/C_Order.java
Labels: porting-branch

#18698 Merge to master from origin/vampire_textbook_uat
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5731580_sys_gh18358_M_Product_Window_show_GTIN.sql
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5731590_sys_edi_cctop_119_v_view_after_merge.sql
Labels: porting-branch

#18709 Fix bug where `C_Order.M_PriceList_ID` was set to the wrong value (CP)
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutOrder.java
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrder.java
  backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java
  backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5731470_sys_gh_Delete_2_legacy_Callouts.sql
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/adempiere/callout/OrderPricingSystem.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/callout/C_Order.java
Labels: ops:without_review_approval, ops:auto_merge

#18712 Reduce flakyness of effortControlPurchaseInvoiceCandidate.feature by fixing AdRefListRepositoryOverJdbc
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/ad_reference/AdRefListRepositoryOverJdbc.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/CCache.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/serviceIssue/S_Issue_StepDef.java
Labels: patch_mgmt

#18711 Merge to master from origin/inner_silence_uat
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/exceptions/AdempiereException.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/BPartnerBankAccountId.java
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/BpartnerRestController.java
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/ShortTermBankAccountIndex.java
  misc/de-metas-common/de-metas-common-bpartner/src/main/java/de/metas/common/bpartner/v2/request/JsonRequestBankAccountUpsertItem.java
  misc/parent-pom/pom.xml
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-metasfresh/src/main/java/de/metas/camel/externalsystems/metasfresh/restapi/MetasfreshRestAPIRouteBuilder.java
Labels: porting-branch

#18723 Display C_InvoiceSchedule.InvoiceDistance because it's used in the BL - Do different UI-related fixes
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/IProcessPrecondition.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessPreconditionChecker.java
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5731790_sys_gh18716_C_Invoice_Schedule_revamp.sql
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/invoice/process/C_InvoiceSchedule_CreateOrUpdate.java
Labels: ops:without_review_approval, ops:auto_merge

#18721 Merge to master from origin/soft_panda_uat
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessPreconditionChecker.java
  backend/de.metas.business/src/main/java/de/metas/invoice/InvoiceScheduleId.java
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5731660_sys_gh18716_C_Invoice_Schedule_revamp.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5731770_sys_gh18716_C_Invoice_Schedule_revamp.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5731790_sys_gh18716_C_Invoice_Schedule_revamp.sql
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/C_InvoiceSchedule.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/ConfigValidator.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/invoice/process/C_InvoiceSchedule_CreateOrUpdate.java
Labels: porting-branch

#18728 Merge to master from origin/vampire_textbook_uat
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/receiptschedule/impl/PlanningHUAttributesUpdater.java
Labels: porting-branch

#18742 debugging fix
  backend/de.metas.report/metasfresh-report-service-standalone/src/main/configs/metasfresh-report.conf
  backend/metasfresh-dist/dist/src/main/configs/metasfresh_server.conf
  backend/metasfresh-dist/dist/src/main/misc/metasfresh_server.conf
  backend/metasfresh-dist/swingui/src/main/resources/RUN_metasfresh.bat
  backend/metasfresh-webui-api/src/main/configs/metasfresh-webui-api.conf
Labels: ops:without_review_approval, ops:auto_merge

#18745 move launch config
  misc/dev-support/idea-runConfigurations/camel-externalsystem-remote-th173-PROD-INT.run.xml
Labels: branch:master, in:5.178_master
