Repository metasfresh/metasfresh, pull requests merged in 2024-09, with the labels that each got.

#18761 Vampire textbook uat fix sscc18 generator
  backend/de.metas.edi/src/main/java/de/metas/edi/sscc18/DesadvLineSSCC18Generator.java
Labels: patch_mgmt

#18754 Set priceUOM on imported Invoice Candidates
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5732150_sys_ic_priceUOM_deactivate_valRule_autoapply.sql
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/invoice/impl/JsonInvoiceService.java
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/invoicecandidates/impl/CreateInvoiceCandidatesService.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/InvoiceCandidateRepository.java
Labels: ops:auto_merge

#18639 Fix invoice-candidate invoicing UOM problem
  backend/de.metas.business/src/main/java/de/metas/quantity/StockQtyAndUOMQtys.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/CucumberLifeCycleSupport.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_BPartner_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/aggregation/C_AggregationItem_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/aggregation/C_AggregationItem_StepDefData.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/aggregation/C_Aggregation_Attribute_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/aggregation/C_Aggregation_Attribute_StepDefData.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/aggregation/C_Aggregation_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/aggregation/C_Aggregation_StepDefData.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_InvoiceLine_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/aggregationAttributes.feature
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/aggregator/standard/DefaultAggregator.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/aggregator/standard/InvoiceCandidateWithInOutLine.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/aggregator/standard/InvoiceCandidateWithInOutLineAggregator.java
Labels: patch_mgmt

#18767 port webapi startup fix from intensive_care_uat
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/report/HUReportProcessInstancesRepository.java
Labels: ops:without_review_approval, ops:auto_merge

#18774 Merge to master from origin/release
  backend/de.metas.edi/src/main/java/de/metas/edi/sscc18/DesadvLineSSCC18Generator.java
Labels: porting-branch

#18790 Callout - have pricing-system be set or updated when bpartner or location changes
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/callout/C_Order.java
Labels: patch_mgmt, ops:without_review_approval, ops:auto_merge

#18706 simplify rabbitmqconfigs
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/impl/EventBusFactory.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/impl/RabbitMQEnqueuer.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/remote/IEventBusQueueConfiguration.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/remote/RabbitMQDestinationResolver.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/event/remote/RabbitMQEventBusConfiguration.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/rabbitMQ/RabbitMQTestConfiguration.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/rabbitMQ/RabbitMQ_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/serviceIssue/S_EffortControl_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/createProductionOrder.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialCockpit/materialCockpit_SO_differentUOMs.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialCockpit/materialCockpit_SO_noProductPlanning.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/production.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/production_and_distribution.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/supplyRequiredQtyViaDistribution.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/supplyRequiredQtyViaProduction.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/supplyRequiredQtyViaPurchase.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/rabbitMQEvents.feature
Labels: ops:auto_merge

#18811 Cucumbers increase wait times
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/createProductionOrder.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/manufacturing.maturing/productMaturing.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/production/multipleProductionCandidates.feature
Labels: ops:without_review_approval, ops:auto_squash_merge

#18812 Fix flaky desadv cucumber
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/edi/ediDesadvPack_with_normal_UOM.feature
Labels: ops:auto_squash_merge

#18814 Fix flaky callOrderContract.feature (make sure schedule exists before…
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/callorder/callOrderContract.feature
Labels: ops:auto_squash_merge

#18828 Merge intensive_care_uat -> master (2024-09-10)
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/ShipperTransportationQuery.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/ShipperTransportationRepository.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/interceptor/M_InOut.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/shippertransportation/ShipperDeliveryService.java
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5732800_sys_gh_18770_add_to_shipper_transportation.sql
Labels: branch:master, in:5.178_master

#18833 Add support for zoom from the other windows (inout, pporder etc) to the HU-Tracing window
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/material/interceptor/transactionevent/TransactionEventFactoryForInOutLine.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/trace/HUTraceEvent.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/trace/HUTraceEventQuery.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/trace/HUTraceEventsService.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/trace/repository/HuTraceEventToDbRecordUtil.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/trace/repository/RetrieveDbRecordsUtil.java
  backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/trace/HUTraceEventsServiceTests.java
  backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/trace/HUTraceRepositoryTests.java
  backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/trace/repository/RetrieveDbRecordsUtilTest.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/trace/HuTraceQueryCreator.java
  backend/de.metas.ui.web.base/src/test/java/de/metas/ui/web/handlingunits/trace/DocumentFilterToHuTraceQueryTest.java
Labels: branch:inner_silence_uat

#18824 Correcting the `TU_per_LU` calculation
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/views/fresh_HU_SSCC_Label_Report.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5732820_sys_gh18823_fresh_HU_SSCC_Label_Report.sql
Labels: branch:intensive_care_uat

#18837 Merge to yoyo_uat from origin/yoyo_hotfix
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/invoicecandidates/impl/InvoiceJsonConverters.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate/C_Invoice_Candidate_StepDef.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/HUShippingFacade.java
  backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/async/spi/impl/InvoiceEnqueueingWorkpackageProcessor.java
  backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/process/C_Invoice_Candidate_EnqueueSelectionForInvoicingAndPDFConcatenating.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoice/InvoiceService.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/CreateInvoiceForModelService.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandidateEnqueuer.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceGenerator.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoicingParams.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidate2WorkpackageAggregator.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueuer.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoicingParams.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/PlainInvoicingParams.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/async/spi/impl/InvoiceCandWorkpackageProcessor.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/async/spi/impl/RecreateInvoiceWorkpackageProcessor.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/ilhandler/CreateCandidatesOnCommitCollector.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/process/C_Invoice_Candidate_EnqueueSelectionForInvoicing.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/process/params/InvoicingParams.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/AbstractICTestSupport.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueueToInvoiceTestBase.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/PlainInvoicingParamsTest.java
  frontend/package.json
  frontend/src/__tests__/utils/dateHelpers.test.js
  frontend/src/assets/css/datepicker.css
  frontend/src/assets/css/datepicker.scss
  frontend/src/assets/css/daterangepicker.css
  frontend/src/assets/css/daterangepicker.scss
  frontend/src/assets/css/styles.css
  frontend/src/components/widget/DateTime/DatePicker.js
  frontend/src/components/widget/DateTime/TetheredDateTime.js
  frontend/src/utils/dateHelpers.js
  frontend/webpack.config.js
  frontend/webpack.prod.js
Labels: porting-branch

#18846 merging after rollout yoyo_uat_31 into yoyo_hotfix
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/dao/selection/QuerySelectionToDeleteHelper.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/dao/housekeeping/spi/impl/ClearTemporaryTables.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5718950_C_Order_CreateCompensationMultiGroups_refreshAllAfterExecution.sql
  backend/de.metas.adempiere.adempiere/serverRoot/de.metas.adempiere.adempiere.serverRoot.base/src/main/java/de/metas/ServerBoot.java
  backend/de.metas.business/src/main/java/de/metas/payment/api/IPaymentBL.java
  backend/de.metas.business/src/main/java/de/metas/payment/api/impl/AbstractPaymentDAO.java
  backend/de.metas.business/src/main/java/de/metas/payment/api/impl/PaymentBL.java
  backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/IESRImportDAO.java
  backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRImportBL.java
  backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/api/impl/ESRImportDAO.java
  backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/dataimporter/ESRDataLoaderUtil.java
  backend/de.metas.payment.esr/src/main/sql/postgresql/system/5638430_sys_gh12945_ImproveImportPerformace.sql
  backend/de.metas.payment.esr/src/main/sql/postgresql/system/5638580_sys_gh12945_ESR_ImportLine_Amount_Numeric.sql
  backend/de.metas.payment.esr/src/main/sql/postgresql/system/5700880_gh16128_fix_index_c_referenceno_ESR.sql
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/process/ProcessInstanceResult.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/process/adprocess/ADProcessPostProcessService.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/process/view/ViewActionInstance.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/events/DocumentWebsocketPublisher.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/events/JSONDocumentChangedWebSocketEvent.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/events/JSONDocumentChangedWebSocketEventCollector.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/DocumentCollection.java
  backend/de.metas.ui.web.base/src/test/java/de/metas/ui/web/window/events/DocumentWebsocketPublisherTest.java
  backend/de.metas.ui.web.base/src/test/java/de/metas/ui/web/window/events/JSONDocumentChangedWebSocketEventCollectorTest.java
  frontend/src/__tests__/actions/ProcessActions.test.js
  frontend/src/__tests__/actions/WindowActions.test.js
  frontend/src/actions/ProcessActions.js
  frontend/src/actions/WindowActions.js
  frontend/src/api/index.js
  frontend/src/api/process.js
  frontend/src/api/window.js
  frontend/src/components/app/Modal.js
  frontend/src/containers/MasterWindow.js
  frontend/src/reducers/windowHandler.js
Labels: branch:master, branch:yoyo_hotfix

#18842 Fix Band height validation build error in `de/metas/docs/label/sscc/label.jrxml`
  backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/label/sscc/label.jrxml
Labels: branch:master, in:5.178_master

#18856 Merge to master from origin/inner_silence_uat
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoice.java
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoiceLine.java
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoiceTax.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/material/interceptor/transactionevent/TransactionEventFactoryForInOutLine.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/trace/HUTraceEvent.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/trace/HUTraceEventQuery.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/trace/HUTraceEventsService.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/trace/repository/HuTraceEventToDbRecordUtil.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/trace/repository/RetrieveDbRecordsUtil.java
  backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/trace/HUTraceEventsServiceTests.java
  backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/trace/HUTraceRepositoryTests.java
  backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/trace/repository/RetrieveDbRecordsUtilTest.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/trace/HuTraceQueryCreator.java
  backend/de.metas.ui.web.base/src/test/java/de/metas/ui/web/handlingunits/trace/DocumentFilterToHuTraceQueryTest.java
Labels: porting-branch

#18840 Merge to master from origin/yoyo_uat
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/invoicecandidates/impl/InvoiceJsonConverters.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate/C_Invoice_Candidate_StepDef.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/HUShippingFacade.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoice/InvoiceService.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/CreateInvoiceForModelService.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/async/spi/impl/InvoiceCandWorkpackageProcessor.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/async/spi/impl/RecreateInvoiceWorkpackageProcessor.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/process/params/InvoicingParams.java
Labels: porting-branch

#18877 Merge to master from origin/vampire_textbook_uat
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/process/rpl/exp/ExportHelper.java
  backend/de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/process/rpl/exp/ExportHelperTest.java
  backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvBL.java
  backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/pack/EDIDesadvPackService.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/HUTransformService.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/report/labels/HULabelConfigFromSysConfigProvider.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/report/labels/HULabelPrintRequest.java
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#18917 Fix jenkins mobile ui build
  misc/services/mobile-webui/mobile-webui-frontend/.gitignore
  misc/services/mobile-webui/mobile-webui-frontend/yarn.lock
Labels: ops:auto_squash_merge

#18927 Sales modular contracts iteration 1
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/lang/SOTrx.java
  backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/I_C_Flatrate_Term.java
  backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/I_ModCntr_Settings.java
  backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/I_ModCntr_Type.java
  backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_C_Flatrate_Term.java
  backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_ModCntr_Settings.java
  backend/de.metas.contracts/src/main/java-gen/de/metas/contracts/model/X_ModCntr_Type.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateDAO.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/ModularContract_Constants.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/purchasecontract/pforderline/SalesOrderLineProFormaPOLogHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/purchasecontract/pforderline/SalesOrderLineProFormaPOModularContractHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/purchasecontract/pp/PPCostCollectorLog.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/purchasecontract/pp/PPCostCollectorModularContractHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/purchasecontract/salesorderline/SOLineForPOLogHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/purchasecontract/salesorderline/SOLineForPOModularContractHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/purchasecontract/shipment/ShipmentLineForPOLogHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/purchasecontract/shipment/ShipmentLineForPOModularContractHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/purchasecontract/shipnotification/ShippingNotificationForPurchaseContractLogsHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/tbd/purchasecontract/shipnotification/ShippingNotificationForPurchaseModularContractHandler.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/interim/invoice/command/InterimInvoiceFlatrateTermCreateCommand.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettingsRepository.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/ModularContractSettingsService.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/settings/interceptor/ModCntr_Settings.java
  backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5733720_computing_method_window_adj.sql
  backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5733730_modular_settings_window_adj.sql
  backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5734360_c_flatrate_term_add_isSOTrx.sql
  backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5734370_c_flatrate_term_add_c_order_constraint.sql
  backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5734380_update_isSOtrx_on_existing_contracts.sql
  backend/de.metas.contracts/src/test/java/de/metas/contracts/modular/settings/ModularContractSettingsRepositoryTest.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/DataTableUtil.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_Settings_StepDef.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/descriptor/DocumentFieldDescriptor.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/Document.java
  backend/de.metas.ui.web.base/src/test/resources/de/metas/ui/web/dataentry/window/descriptor/factory/DataEntryTabLoaderTest.snap
Labels: ops:auto_squash_merge

#18986 Intensive care uat materialdispo tweaks
  backend/de.metas.business/src/main/java/de/metas/uom/IUOMDAO.java
  backend/de.metas.business/src/main/java/de/metas/uom/impl/UOMDAO.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/C_Order_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/DataTableRow.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/StepDefDataIdentifier.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/billofmaterial/PP_Product_Bom_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/voidOrder.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/production/productionCandidate.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/production/productionCandidate_with_BOM_recursion.feature
  backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5735040_sys_gh18935_tweaks.sql
  backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5735080_sys_gh18935_tweaks.sql
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/material/interceptor/M_ShipmentSchedule_PostMaterialEvent.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#19005 EDI tweaks - Adapt to new customer- and HU-constellations
  backend/de.metas.edi/src/main/java/de/metas/edi/model/validator/M_InOut.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/generichumodel/HU.java
  misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/commons/DesadvSettings.java
  misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/commons/route/exports/EDIExportCommonRoute.java
Labels: ops:without_review_approval
