Repository metasfresh/metasfresh, pull requests merged in 2024-07, with the labels that each got.

#18377 Fix processes are not displayed with reject message in grid view
  frontend/src/api/view.js
Labels: patch_mgmt

#18429 Replace recordRef with a proper object when intercepting unposted match invoices
  backend/de.metas.acct.base/src/main/java/de/metas/acct/interceptor/AcctMatchInvListener.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/IFactAcctDAO.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/impl/FactAcctDAO.java
  backend/de.metas.business/src/main/java/de/metas/invoice/matchinv/service/MatchInvoiceRepository.java
  backend/de.metas.business/src/main/java/de/metas/invoice/matchinv/service/MatchInvoiceService.java
Labels: ops:dont_auto_merge

#18529 Fix cockpit stock production and try to fix RabbitMQ not respecting FIFO
  backend/.gitignore
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsBL.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsBL.java
  backend/de.metas.manufacturing/src/main/java/de/metas/manufacturing/acct/Doc_PPCostCollector.java
  backend/de.metas.manufacturing/src/main/java/org/eevolution/model/MPPCostCollector.java
  backend/de.metas.report/metasfresh-report-service-standalone/README.md
  backend/de.metas.report/metasfresh-report-service-standalone/src/main/resources/config/application.properties
  backend/de.metas.servicerepair.base/src/main/java/de/metas/servicerepair/customerreturns/RepairCustomerReturnsService.java
  backend/metasfresh-dist/dist/src/main/docker/app/configs/application.properties
  backend/metasfresh-webui-api/src/main/resources/application.properties
  misc/dev-support/README.md
  misc/dev-support/application.properties/README.md
  misc/dev-support/application.properties/metasfresh/backend/de.metas.report/metasfresh-report-service-standalone/src/main/resources/application.properties
  misc/dev-support/application.properties/metasfresh/backend/metasfresh-dist/serverRoot/application.properties
  misc/dev-support/application.properties/metasfresh/backend/metasfresh-webui-api/application.properties
  misc/dev-support/application.properties/metasfresh/misc/services/mobile-webui/mobile-webui-frontend/public/config.js
Labels: ops:auto_merge

#18570 port unit test fix from master
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/AbstractNewAggregationEngineTests.java
Labels: ops:without_review_approval, ops:auto_merge
