Repository metasfresh/metasfresh, pull requests merged in 2024-04, with the labels that each got.

#17738 Merge to master from 647473ca13402ad4d9c47a30922e0ad1f0beacf9
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/exp/RabbitMqExportProcessor.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/imp/RabbitMqListener.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/13-org.adempiere.process.rpl/5720360_sys_cli_fix_and_cleanup_rpl_processors.sql
  misc/services/camel/de-metas-camel-edi/src/main/resources/application.properties
Labels: ops:dont_auto_merge

#17790 Merge to soft_panda_uat from origin/soft_panda_hotfix
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/13-org.adempiere.process.rpl/5720360_sys_cli_fix_and_cleanup_rpl_processors.sql
Labels: ops:dont_auto_merge

#17806 Merge to master from origin/release
  backend/de.metas.acct.base/src/main/java/de/metas/acct/aggregation/legacy/impl/PlainLegacyFactAcctLogDAO.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/organization/LocalDateAndOrgId.java
  backend/de.metas.business/src/main/java/org/eevolution/api/PPOrderDocBaseType.java
  backend/de.metas.business/src/main/java/org/eevolution/api/impl/ProductBOMDAO.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/dunning/C_Dunning_Candidate_StepDef.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/IDunnableDoc.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/IDunningBL.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/IDunningContext.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DefaultDunningCandidateProducer.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DefaultDunningProducer.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DunnableDoc.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DunningBL.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DunningContext.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/invoice/api/IInvoiceSourceDAO.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/invoice/api/impl/InvoiceSourceDAO.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/invoice/spi/impl/InvoiceSource.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/process/C_Dunning_Candidate_Create.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/spi/impl/AbstractDunnableSource.java
  backend/de.metas.dunning/src/test/java/de/metas/dunning/DunningTestBase.java
  backend/de.metas.dunning/src/test/java/de/metas/dunning/api/impl/DefaultDunningCandidateProducerFactoryTest.java
  backend/de.metas.dunning/src/test/java/de/metas/dunning/api/impl/DefaultDunningCandidateProducerTest.java
  backend/de.metas.dunning/src/test/java/de/metas/dunning/api/impl/PlainDunningContext.java
  backend/de.metas.dunning/src/test/java/de/metas/dunning/invoice/api/impl/DunnableDocBuilder.java
  backend/de.metas.dunning/src/test/java/de/metas/dunning/spi/impl/BaseDunnableSourceTest.java
  backend/de.metas.dunning/src/test/java/de/metas/dunning/test/integration/TestDunning.java
  backend/de.metas.manufacturing/src/main/java/org/eevolution/api/impl/PPOrderBL.java
  backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/service/CreateUpdateOrderCandidateCommand.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/pricing/rules/ManualPricePricingRule.java
  frontend/src/__tests__/actions/ProcessActions.test.js
  frontend/src/__tests__/actions/WindowActions.test.js
  frontend/src/api/index.js
  frontend/src/reducers/windowHandler.js
Labels: branch:master, ops:dont_auto_merge

#17822 Merge to release from origin/release_5.175
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/exp/RabbitMqExportProcessor.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/imp/RabbitMqListener.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/13-org.adempiere.process.rpl/5720360_sys_cli_fix_and_cleanup_rpl_processors.sql
  misc/services/camel/de-metas-camel-edi/src/main/resources/application.properties
Labels: ops:dont_auto_merge

#17828 Avoid NPE on webapi startup
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/notification/UserNotificationDetailMessageFormat.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/InterfaceWrapperHelper.java
  backend/de.metas.business/src/main/java/de/metas/document/engine/impl/AbstractDocumentBL.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/notification/UserNotificationDetailMessageFormat.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/notification/UserNotificationsQueue.java
Labels: ops:without_review_approval

#17832 Merge to release from origin/release_5.175
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/notification/UserNotificationDetailMessageFormat.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/InterfaceWrapperHelper.java
  backend/de.metas.business/src/main/java/de/metas/document/engine/impl/AbstractDocumentBL.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/notification/UserNotificationDetailMessageFormat.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/notification/UserNotificationsQueue.java
Labels: ops:dont_auto_merge, porting-branch

#17827 Merge to master from origin/release
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/notification/UserNotificationDetailMessageFormat.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/InterfaceWrapperHelper.java
  backend/de.metas.business/src/main/java/de/metas/document/engine/impl/AbstractDocumentBL.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/notification/UserNotificationDetailMessageFormat.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/notification/UserNotificationsQueue.java
Labels: ops:dont_auto_merge

#17830 Merge to master from origin/soft_panda_uat
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/model/InterfaceWrapperHelper.java
  backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/ch/lagerkonf/invoicing/impl/QualityInvoiceLineGroupsBuilder.java
  backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/IVendorInvoicingInfo.java
  backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/MaterialTrackingAsVendorInvoicingInfo.java
  backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/PlainVendorInvoicingInfo.java
  backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/PricingContextBuilder.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/sql/SqlDefaultDocumentFilterConverter.java
Labels: ops:dont_auto_merge

#17759 Update Jasper to latest version `6.21.2`
  backend/de.metas.adempiere.adempiere/base/pom.xml
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_R_Request.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_R_Request.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/pdf/Document.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/Trace.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/report/ExecuteReportStrategyUtil.java
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/MRequest.java
  backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/api/impl/BPartnerBL.java
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Current_Vs_Previous_Pricelist_Comparison_Report.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Current_Vs_Previous_Pricelist_Comparison_Report_With_PP_PI.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5721390_sys_gh2819_Current_Vs_Previous_Pricelist_Comparison_Report.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5721400_sys_gh2819_Current_Vs_Previous_Pricelist_Comparison_Report_With_PP_PI.sql
  backend/de.metas.inbound.mail/src/main/java/de/metas/inbound/mail/request/RequestFromInboundEMailListener.java
  backend/de.metas.payment.esr/src/main/java/de/metas/payment/spi/impl/ESRCreaLogixStringParser.java
  backend/de.metas.printing/de.metas.printing.base/pom.xml
  backend/de.metas.procurement.base/src/main/java/de/metas/procurement/base/order/impl/PMMPricingAware_C_OrderLine.java
  backend/de.metas.report/de.metas.report.jasper.client/pom.xml
  backend/de.metas.report/de.metas.report.jasper.commons/pom.xml
  backend/de.metas.report/metasfresh-report-service/pom.xml
  backend/de.metas.shipper.gateway.derkurier/src/main/java/de/metas/shipper/gateway/derkurier/misc/ParcelNumberGenerator.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/crm/interceptor/R_Request.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/request/process/WEBUI_CreateRequest.java
  misc/parent-pom/pom.xml
Labels: ops:dont_auto_merge

#17860 Change CSV delimiter to ; for external system PCM
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/bpartner/model/BPartnerRow.java
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/product/model/ProductRow.java
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/purchaseorder/model/PurchaseOrderRow.java
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/warehouse/model/WarehouseRow.java
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/bpartner/10_BPartner_ImportFile.csv
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/product/10_Product_ImportFile.csv
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/purchaseorder/10_PurchaseOrder_ImportFile.csv
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/warehouse/10_Warehouse_ImportFile.csv
Labels: ops:without_review_approval

#17861 Fix creation of one invoice from orders with different externalHeaderIds
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
Labels: ops:without_review_approval

#17862 Support decimal comma instead of point in PCM purchase order items
  misc/services/camel/de-metas-camel-externalsystems/common/src/main/java/de/metas/camel/externalsystems/common/CamelProcessorUtil.java
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/purchaseorder/model/PurchaseOrderRow.java
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/purchaseorder/10_PurchaseOrder_ImportFile.csv
Labels: ops:without_review_approval

#17882 super-minor comment-improvment
  backend/de.metas.edi/src/main/sql/postgresql/ddl/views/edi_cctop_invoic_v_view.sql
Labels: ops:without_review_approval

#17895 externalsystems-PCM - fix a date formatting error and Hopefully finally found a twist to make the route wait until master data fiels are gone
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/purchaseorder/GetPurchaseOrderFromFileProcessStrategy.java
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/purchaseorder/GetPurchaseOrderFromFileRouteBuilder.java
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/purchaseorder/ImportConstants.java
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/purchaseorder/StallWhileMasterdataFilesExistPolicy.java
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/java/de/metas/camel/externalsystems/pcm/purchaseorder/GetPurchaseOrderFromFileRouteBuilderTest.java
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/purchaseorder/csvFileWithError/10_WithError_PurchaseOrder_ImportFile.csv
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/test/resources/de/metas/camel/externalsystems/pcm/purchaseorder/happyFlow/10_PurchaseOrder_ImportFile.csv
Labels: ops:without_review_approval

#17896 work around a missing response body & port another fix from master
  backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/remoteorder/RealVendorGatewayInvoker.java
  backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/remoteorder/VendorGatewayInvokerFactory.java
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-pcm-file-import/src/main/java/de/metas/camel/externalsystems/pcm/purchaseorder/GetPurchaseOrderFromFileRouteBuilder.java
Labels: ops:without_review_approval

#17898 when creating a warehouse via API - also create default locator
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/IWarehouseDAO.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseDAO.java
Labels: ops:without_review_approval

#17920 Merge to soft_panda_uat from origin/soft_panda_hotfix
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/13-org.adempiere.process.rpl/5720360_sys_cli_fix_and_cleanup_rpl_processors.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5722400_sys_add_uom_conversion_MM_to_LM.sql
  backend/de.metas.material/cockpit/src/main/java/de/metas/material/cockpit/view/eventhandler/ReceiptScheduleEventHandler.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/rowfactory/MainRowBucket.java
Labels: ops:dont_auto_merge, porting-branch
