Repository metasfresh/metasfresh, pull requests merged in 2024-10, with the labels that each got.

#19012 Merge to master from origin/vampire_textbook_uat
  backend/de.metas.edi/src/main/java/de/metas/edi/model/validator/M_InOut.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/generichumodel/HU.java
  misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/commons/DesadvSettings.java
  misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/commons/route/exports/EDIExportCommonRoute.java
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#19023 Add the EDIFACT-packaging-code "CT"
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5735440_cli_EDIFACT_7065_Packaging_Code_CT.sql
Labels: ops:without_review_approval, ops:auto_squash_merge

#19034 Merge tasty_ham_hotfix to tasty_ham_uat
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/trace/HUTraceEventsService.java
Labels: branch:master, branch:tasty_ham_uat

#19035 merge tasty_ham branches to master
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/trace/HUTraceEventsService.java
Labels: branch:master

#19046 add inner_silence_hotfix to mergify and testspace
  .mergify.yml
  .testspace.yml
Labels: ops:auto_squash_merge

#19064 Merge to master from origin/yoyo_uat
  backend/de.metas.material/dispo-service/src/main/sql/postgresql/system/75-material-dispo/5735840_sys_SysConfig_EnqueueMaterialEvents.sql
  backend/de.metas.material/event/src/main/java/de/metas/material/event/PostMaterialEventService.java
  misc/dev-support/docker/infrastructure/env-files/yoyo_uat.env
Labels: porting-branch

#19072 Port fix for flaky cucumber-test from master-branch
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate/C_Invoice_Candidate_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/edi/ediDesadvPack_with_TU_UOM.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/edi/ediDesadvPack_with_normal_UOM.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/edi/ediExport.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceCandidateOverrideFields.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceCandidateQtyToInvoiceOverride.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoiceRules.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoicecandidate/item/purchaseItemInvoiceCandidate.feature
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#19081 Desadv sort packs and items
  misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/desadvexport/ecosio/EcosioDesadvRoute.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#19091 Merge to tasty_ham_uat from origin/tasty_ham_hotfix
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_WF_Node.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/I_PP_Order_Node.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/eevolution/model/X_PP_Order_Node.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pporder/PP_Order_StepDef.java
  backend/de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/X_PP_Order_Qty.java
  backend/de.metas.util/src/test/java/de/metas/util/collections/CollectionUtilsTest.java
Labels: porting-branch

#19111 merging after rollout yoyo_uat_32 into yoyo_hotfix
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_OrderLine.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_OrderLine.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/IDocTypeBL.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/impl/DocTypeBL.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5719010_C_Order_AddDiscountCompensationLine_refreshAllAfterExecution.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5719030_C_OrderLine_ManualCompensationLinePosition.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5719040_sysconfig_ManualCompensationLinePosition.sql
  backend/de.metas.business/src/main/java/de/metas/order/IOrderBL.java
  backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/Group.java
  backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupCompensationLine.java
  backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupCompensationLineCreateRequest.java
  backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupCompensationLineCreateRequestFactory.java
  backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/GroupCreator.java
  backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/ManualCompensationLinePosition.java
  backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/OrderGroupCompensationUtils.java
  backend/de.metas.business/src/main/java/de/metas/order/compensationGroup/OrderGroupRepository.java
  backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
  backend/de.metas.business/src/main/java/de/metas/order/process/C_Order_AddDiscountCompensationLine.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/interceptor/C_Order.java
  backend/de.metas.material/dispo-service/src/main/sql/postgresql/system/75-material-dispo/5735840_sys_SysConfig_EnqueueMaterialEvents.sql
  backend/de.metas.material/event/src/main/java/de/metas/material/event/PostMaterialEventService.java
  misc/dev-support/docker/infrastructure/env-files/yoyo_uat.env
Labels: branch:master

#19133 Merge to master from origin/soft_panda_uat
  backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/invoicecandidate/spi/impl/FreshQuantityDiscountAggregator.java
  backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/IMaterialTrackingPPOrderDAO.java
  backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/ch/lagerkonf/ILagerKonfQualityBasedConfig.java
  backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/ch/lagerkonf/impl/HardCodedQualityBasedConfig.java
  backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/ch/lagerkonf/impl/RecordBackedQualityBasedConfig.java
  backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/ch/lagerkonf/invoicing/impl/QualityInvoiceLineGroupsBuilder.java
  backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/ic/spi/impl/PPOrder2InvoiceCandidatesProducer.java
  backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/MaterialTrackingDocuments.java
  backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/spi/IQualityBasedConfig.java
Labels: porting-branch

#19185 master_int_inner_silence_uat_sales_modcntr
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/DataTableRow.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/C_Flatrate_Term_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_Settings_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_Specific_Price_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/contract/ModCntr_Type_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoice/C_Invoice_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/pricing/M_PriceList_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipment/M_InOut_StepDef.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_Split_StepDefData.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/shipmentschedule/M_ShipmentSchedule_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/processed/purchaseProcessedProduct.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/processed/salesProcessedProduct.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/contract/moduleLog/raw/purchaseRawProduct.feature
Labels: ops:auto_merge_commit

#19254 Fix that IMP_ProcessorLogs were created with AD_Client_ID=0 so there was an ex when open ing detail view
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/trx/api/ITrxManager.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/api/impl/IMPProcessorBL.java
  misc/dev-support/docker/infrastructure/env-files/intensive_care_uat.env
Labels: ops:without_review_approval, ops:auto_squash_merge
