Repository metasfresh/metasfresh, pull requests merged in 2024-12, with the labels that each got.

#19482 Anpassung der Namen von PDF-Dateien
  backend/de.metas.report/metasfresh-report-service/src/main/java/de/metas/report/jasper/JasperEngine.java
Labels: ops:auto_squash_merge

#19510 Guard against two orders referring to the same DESADV
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5741090_sys_gh18358_fix_EDI_Desadv_DatePromised_SqlColumn.sql
Labels: ops:without_review_approval, ops:auto_squash_merge

#19522 add run-configs to new_dawn_uat run-config-folder
  misc/dev-support/idea-runConfigurations/ServerBoot - new_dawn_uat.run.xml
  misc/dev-support/idea-runConfigurations/SwingUIApplication - new_dawn_uat.run.xml
  misc/dev-support/idea-runConfigurations/WebRestApiApplication - new_dawn_uat.run.xml
  misc/dev-support/idea-runConfigurations/camel-externalsystems - new_dawn_uat.run.xml
Labels: ops:without_review_approval, ops:auto_squash_merge

#19559 Remove the StartNewYear columns from recently ported SQL-files
  backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5668780_SAP_GLJournal.sql
  backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5668880_SAP_GLJournalLine.sql
  backend/de.metas.acct.base/src/main/sql/postgresql/system/43-de.metas.acct/5697490_Fact_Acct_UserChange.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5651680_sys_M_CostRevaluation_Detail.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5675710_AD_UI_ElementGroup_AddField_IsNewUIElementsOnly_default_Y.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647750_sys_gh13319_final_product_price.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5647770_sys_gh13319_final_product_price.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5675760_C_Order_Cost.sql
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5676010_M_InOut_Cost.sql
Labels: ops:without_review_approval, ops:auto_squash_merge

#19598 Merging `new_dawn_uat`
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/exceptions/DBException.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/model/GridFieldVO.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessInfo.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5741330_sys_recreate_AD_Field_V_views.sql
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/process/C_OLCandEnqueueForSalesOrderCreation.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/process/WEBUI_Order_ProductsProposal_Launcher.java
Labels: ops:auto_merge_commit

#19629 EDI export status and EDI Lieferavis Pack
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5741670_sys_gh19624_EDI_Desadv_Pack_M_InOut_ID.sql
  misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/desadvexport/ecosio/EcosioDesadvRoute.java
Labels: ops:auto_squash_merge

#19630 Merge to master from origin/soft_panda_uat
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipping/process/M_ShippingPackage_CreateFromPickingSlots.java
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#19656 Port fix where C_Invoice_Candidate.C_Payment_Term_ID is made mandatory
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5684560_sys_gh14602_MigrateInvoiceCandidates.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5684561_sys_gh14602_MakePaymentTermMandatoryInInvoiceCandidates.sql
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/CalloutInvoice.java
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/MOrder.java
  backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/IPaymentTermRepository.java
  backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/PaymentTerm.java
  backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/PaymentTermService.java
  backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/impl/PaymentTermQuery.java
  backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/impl/PaymentTermRepository.java
  backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/interceptor/C_OrderLine.java
  backend/de.metas.business/src/test/java/de/metas/payment/grossprofit/PaymentTermGrossProfitComponentTest.java
  backend/de.metas.contracts/src/test/java/de/metas/contracts/impl/FlatrateTermDataFactory.java
  backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/process/InvokeShopware6Action.java
  backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/process/InvokeShopwareService.java
  backend/de.metas.purchasecandidate.base/src/test/java/de/metas/purchasecandidate/PurchaseDemandWithCandidatesServiceTest.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/I_C_Invoice_Candidate.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateHandlerBL.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/inout/invoicecandidate/M_InOutLine_HandlerTest.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/AbstractICTestSupport.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/C_Invoice_Candidate_Builder.java
Labels: ops:auto_squash_merge

#19665 Merge to hard_encoded_hotfix from origin/hard_encoded_uat
  .github/workflows/cicd.yaml
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5737850_sys_C_BPartner_MoveToAnotherOrg_Mass.sql
  backend/de.metas.business/src/main/java/de/metas/allocation/api/impl/AllocationBL.java
  backend/de.metas.business/src/main/java/de/metas/allocation/api/impl/AllocationDAO.java
  backend/de.metas.business/src/main/java/de/metas/banking/invoice_auto_allocation/BankAccountInvoiceAutoAllocRules.java
  backend/de.metas.business/src/test/java/de/metas/banking/invoice_auto_allocation/BankAccountInvoiceAutoAllocRulesTest.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/bpartner/process/C_BPartner_MoveToAnotherOrg_Mass.java
  docker-builds/Dockerfile.mobile
  docker-builds/Dockerfile.mobile.compat
  docker-builds/Dockerfile.procurement.frontend
  docker-builds/compose/compose.yml
  docker-builds/cucumber/compose.yml
  docker-builds/cucumber/run.cmd
  docker-builds/cucumber/stop.cmd
  docker-builds/db/scripts/adjust-config.sql
  docker-builds/health/apiHealthChecks.sh
  docker-builds/health/containerHealthCheck.sh
  frontend/src/__tests__/utils/dateHelpers.test.js
  frontend/src/components/widget/DateTime/DatePicker.js
  frontend/src/components/widget/DateTime/TetheredDateTime.js
  frontend/src/components/widget/List/RawList.js
  frontend/src/utils/dateHelpers.js
  misc/services/mobile-webui/mobile-webui-frontend/.gitignore
  misc/services/mobile-webui/mobile-webui-frontend/package.json
  misc/services/mobile-webui/mobile-webui-frontend/yarn.lock
  misc/services/procurement-webui/procurement-webui-frontend/package.json
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#19668 master_int_new_dawn_uat_pick_terminal_fix
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_InvoiceLine.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_InOutLine.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5684560_sys_gh14602_MigrateInvoiceCandidates.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5684561_sys_gh14602_MakePaymentTermMandatoryInInvoiceCandidates.sql
  backend/de.metas.business/src/main/java-legacy/org/compiere/model/MInvoiceLine.java
  backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/PaymentTerm.java
  backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/PaymentTermService.java
  backend/de.metas.business/src/main/java/de/metas/payment/paymentterm/impl/PaymentTermRepository.java
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5741740_sys_gh19624_edi_cctop_119_v.sql
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5741840_sys_replaceQtyCU_param.sql
  backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/process/InvokeShopwareService.java
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5741820_sys_gh19649_PackingMaterial_Win_Update.sql
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/report/labels/HULabelPrintCommand.java
  backend/de.metas.purchasecandidate.base/src/test/java/de/metas/purchasecandidate/PurchaseDemandWithCandidatesServiceTest.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/C_Invoice_Candidate_Builder.java
  misc/services/mobile-webui/mobile-webui-frontend/src/__tests__/utils/numbers.test.js
  misc/services/mobile-webui/mobile-webui-frontend/src/apps/pos/containers/order_panel/GetCatchWeightModal.jsx
  misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScanScreen.jsx
  misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickStepScanScreen.jsx
  misc/services/mobile-webui/mobile-webui-frontend/src/utils/numberUtils.js
  misc/services/mobile-webui/mobile-webui-frontend/src/utils/numbers.js
Labels: ops:without_review_approval, ops:auto_merge_commit
