Repository metasfresh/metasfresh, pull requests merged in 2024-06, with the labels that each got.

#18119 Fix SQL problem about exporting INVOIC
  backend/de.metas.edi/src/main/sql/postgresql/ddl/views/edi_cctop_119_v_view.sql
  backend/de.metas.edi/src/main/sql/postgresql/ddl/views/edi_cctop_invoic_500_v_view.sql
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5725160_sys_fix_edi_cctop_119_v_and_end_cctop_invoic_500_v.sql
Labels: ops:without_review_approval

#18168 master_int_inner_silence_defInv_fixes
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/averageonshippedqty/AbstractUENShipmentLineLog.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/definitiveinvoice/AbstractDefinitiveInvoiceComputingMethod.java
  backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5725790_sys_add_computing_method_to_log_window.sql
Labels: ops:without_review_approval

#18202 Fix caching problem in BPartnerDAO
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/CacheInvalidationRemoteHandler.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/model/CacheInvalidateMultiRequest.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/model/CacheInvalidateRequest.java
Labels: ops:without_review_approval

#18203 Merge to master from origin/soft_panda_uat
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/InvoiceCandidateIdsSelection.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/InvoiceCandidate_Constants.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationDAO.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/async/spi/impl/UpdateInvalidInvoiceCandidatesWorkpackageProcessor.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/C_Invoice_Candidate.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/aggregator/standard/InvoiceCandidateWithInOutLine.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/InvoiceCandidateIdsSelectionTest.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/PlainAggregationDAO.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/PlainInvoiceCandDAO.java
Labels: ops:dont_auto_merge, porting-branch

#18209 Prevend DBuniqueConstraintException when updating invoice candidates …
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandDAO.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/InvoiceCandidateIdsSelection.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/InvoiceCandidate_Constants.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/AggregationDAO.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBLCreateInvoices.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandDAO.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandInvalidUpdater.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandidateEnqueuer.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/async/spi/impl/UpdateInvalidInvoiceCandidatesWorkpackageProcessor.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/modelvalidator/C_Invoice_Candidate.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/aggregator/standard/InvoiceCandidateWithInOutLine.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/InvoiceCandidateIdsSelectionTest.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/PlainAggregationDAO.java
Labels: ops:without_review_approval

#18213 JsonPersisterService: Fix bug when IBAN is updated
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/automaticlinksharing/RecordToReferenceProviderService.java
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/AttachmentInvoiceCandidateListener.java
  misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/attachment/JsonAttachmentRequest.java
Labels: patch_mgmt

#18220 Merge to master from origin/inner_silence_uat
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/attachments/automaticlinksharing/RecordToReferenceProviderService.java
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/ModularContractProvider.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/spi/impl/AttachmentInvoiceCandidateListener.java
Labels: ops:dont_auto_merge, porting-branch

#18223 Merge to master from origin/intensive_care_uat
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerBL.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerBL.java
Labels: ops:dont_auto_merge, porting-branch

#18224 If the pricing-engine is handed a PriceListId, then it shall use it
  backend/de.metas.business/src/main/java/de/metas/pricing/service/IPriceListBL.java
  backend/de.metas.business/src/main/java/de/metas/pricing/service/IPriceListDAO.java
  backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListBL.java
  backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PriceListDAO.java
  backend/de.metas.business/src/main/java/de/metas/pricing/service/impl/PricingBL.java
  backend/de.metas.materialtracking/src/main/java/de/metas/materialtracking/qualityBasedInvoicing/impl/QualityInspectionHandlerDAO.java
Labels: patch_mgmt

#18215 Merge to master from origin/middle_ages_uat
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/IBPartnerDAO.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/bpartner/service/impl/BPartnerDAO.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/model/CacheInvalidateMultiRequest.java
  backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateBL.java
  backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5726080_sys_gh17795_AD_RelationType_C_Invoice_to_C_Flatrate_Term.sql
  backend/de.metas.contracts/src/main/sql/postgresql/system/50-de.metas.contracts/5726090_sys_gh17795_AD_RelationType_C_Invoice_to_C_Flatrate_Term.sql
Labels: ops:dont_auto_merge, porting-branch

#18241 Notify about created virtual HU on shipment
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/CreateVirtualInventoryWithQtyReq.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/inventory/InventoryService.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/M_InOut.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/shipmentschedule/api/ShipmentScheduleWithHUService.java
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5726270_sys_virtual_hu_inventory_created_msg.sql
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5726310_sys_add_virtual_inventory_hu_msg_update.sql
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/picking/pickingslot/process/WEBUI_Picking_With_M_Source_HU_Base.java
Labels: ops:dont_auto_merge

#18232 Merge to master from origin/big_coconut_uat
  backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/57262309_sys_fix_C_Invoice_Candidate_HeaderAggregation_InvoicingGroupNo_ft.sql
Labels: ops:dont_auto_merge, porting-branch

#18258 Fix bug where ICs attributes were not taken into account when computing the price
  backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/dataEntry/invoice/FlatrateDataEntryHandler.java
Labels: ops:without_review_approval

#18261 Merge to master from origin/middle_ages_uat
  backend/de.metas.contracts/src/main/java/de/metas/contracts/flatrate/dataEntry/invoice/FlatrateDataEntryHandler.java
Labels: ops:dont_auto_merge, porting-branch

#18263 Inactive products with qty in warehouse
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHUQueryBuilder.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/model/validator/M_Product.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/storage/spi/hu/impl/HUStorageEngine.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/storage/spi/hu/impl/HUStorageQuery.java
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5726520_sys_gh18254_Inactive_Products_With_Stock_AD_Message.sql
  backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddorder/process/DD_Order_GenerateRawMaterialsReturn.java
  backend/de.metas.storage/src/main/java/de/metas/storage/IStorageEngine.java
  backend/de.metas.storage/src/main/java/de/metas/storage/IStorageQuery.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/document/filter/DocumentFilterList.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/filters/MaterialCockpitFilters.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/filters/ProductFilterUtil.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/material/cockpit/filters/ProductFilterVO.java
Labels: ops:dont_auto_merge

#18299 webui frontend: empty view cell shall be edited by simply start writing (same as when the cell is not empty)
  frontend/src/components/table/TableCell.js
Labels: patch_mgmt

#18328 Master intensive care uat 06262024
  backend/de.metas.contracts/src/main/java/de/metas/contracts/subscription/impl/SubscriptionBL.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/adempiere/gui/search/impl/OLCandHUPackingAware.java
  backend/de.metas.salescandidate.base/src/main/java-gen/de/metas/ordercandidate/model/I_C_OLCand.java
  backend/de.metas.salescandidate.base/src/main/java-gen/de/metas/ordercandidate/model/X_C_OLCand.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/invoicecandidate/spi/impl/C_OLCand_Handler.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/IOLCandBL.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/IOLCandEffectiveValuesBL.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCand.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/OLCandOrderFactory.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/impl/OLCandBL.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/impl/OLCandEffectiveValuesBL.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/modelvalidator/C_OLCand.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/spi/impl/DefaultOLCandValidator.java
  backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5727280_sys_gh18320_OLCand_QtyEntered_Override.sql
  backend/de.metas.salescandidate.base/src/main/sql/postgresql/system/45-de.metas.salescandidate/5727320_sys_gh18320_OLCand_QtyEntered_Override.sql
Labels: ops:dont_auto_merge
