Repository metasfresh/metasfresh, pull requests merged in 2024-11, with the labels that each got.

#19292 Merge to intensive_care_uat_update from other branches
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Ingredients.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product_Ingredients.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Ingredients.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product_Ingredients.java
  backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/product/M_Product_CopyTemplateCustomizer.java
Labels: ops:without_review_approval, porting-branch, ops:auto_squash_merge

#19296 fix SQL-problem (AD_Sequence.StartNewYear)
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5726250_sys_gh18259_add_EDI_Desadvline_InoutLine.sql
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5726420_sys_gh18259_Add_AD_Table_M_InOut_DesadvLine_Pack_V.sql
Labels: ops:without_review_approval, ops:auto_squash_merge

#19299 RabbitMQ prefetch size and consumer count (#19249)
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/cache/CacheInvalidationRemoteHandler.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/util/agg/key/AbstractHeaderAggregationKeyBuilder.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/server/rpl/imp/RabbitMqListener.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/IShipmentScheduleEffectiveBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inoutcandidate/api/impl/ShipmentScheduleEffectiveBL.java
  backend/de.metas.util/src/main/java/org/adempiere/util/agg/key/impl/AggregationKeyRegistry.java
  backend/metasfresh-dist/base/src/main/resources/application.properties
  backend/metasfresh-webui-api/src/main/resources/application.properties
Labels: ops:without_review_approval, ops:auto_squash_merge

#19293 when cloning a product, also clone its ingredients (#19289)
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Ingredients.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_Product_Ingredients.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Ingredients.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_Product_Ingredients.java
  backend/de.metas.fresh/de.metas.fresh.base/src/main/java/de/metas/fresh/product/M_Product_CopyTemplateCustomizer.java
Labels: ops:auto_merge_commit

#19324 fix stack overflow error
  backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/ExternalSystemConfigRepo.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#19325 Merge to master from origin/middle_ages_uat
  backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/ExternalSystemConfigRepo.java
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#19350 Master merge soft panda uat 14112024
  .github/workflows/cicd.yaml
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/mail/send_mail.feature
  docker-builds/cucumber/compose.yml
Labels: ops:without_review_approval, ops:auto_merge_commit

#19367 Fix an error creating migration-logs
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/migration/logger/MigrationScriptFileLogger.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/migration/rest/MigrationScriptRestControllerTemplate.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#19373 Merge to master from origin/inner_silence_uat
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/migration/logger/MigrationScriptFileLogger.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/migration/rest/MigrationScriptRestControllerTemplate.java
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#19375 Merge to master from origin/release
  backend/de.metas.banking/de.metas.banking.camt53/src/main/java/de/metas/banking/camt53/wrapper/v02/BatchReportEntry2Wrapper.java
  backend/de.metas.banking/de.metas.banking.camt53/src/main/java/de/metas/banking/camt53/wrapper/v04/BatchReportEntry4Wrapper.java
  backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/inout/report_description.jrxml
  backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/invoice/report_description.jrxml
  backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/order/report_description.jrxml
  backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/invoice/report_description.jrxml
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#19449 Inner silence hotfix set docstatus in single invoice query
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5740640_Extend_Index_c_invoice_uc_externalId_org.sql
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v1/payment/JsonPaymentService.java
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/invoice/review/JsonInvoiceReviewService.java
  backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/v2/invoice/JsonInvoiceReviewUpsertItem.java
  backend/de.metas.util/src/main/java/de/metas/util/Check.java
  misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/SwaggerDocConstants.java
  misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/invoice/JsonInvoicePaymentCreateRequest.java
  misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/invoice/JsonPaymentAllocationLine.java
Labels: ops:auto_squash_merge, ops:auto_merge_commit

#19453 Intensive care uat introduce cc
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_User.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_User.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/email/MailService.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5734590_sys_AD_User_CC.sql
  backend/de.metas.business/src/main/java/de/metas/letters/model/MADBoilerPlate.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/mail/MailRestController.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/mail/WebuiMailRepository.java
Labels: ops:auto_squash_merge

#19454 Fix problem for API invoice review
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/invoice/review/JsonInvoiceReviewService.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceReview.feature
Labels: ops:without_review_approval, ops:auto_squash_merge

#19452 merging after rollout inner_silence_hotfix_06 into inner_silence_uat
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5740640_Extend_Index_c_invoice_uc_externalId_org.sql
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v1/payment/JsonPaymentService.java
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/invoice/review/JsonInvoiceReviewService.java
  backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/v2/invoice/JsonInvoiceReviewUpsertItem.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceReview.feature
  backend/de.metas.util/src/main/java/de/metas/util/Check.java
  misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/SwaggerDocConstants.java
  misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/invoice/JsonInvoicePaymentCreateRequest.java
  misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/invoice/JsonPaymentAllocationLine.java
Labels: ops:without_review_approval, ops:auto_merge_commit

#19461 Merge to master from origin/inner_silence_uat
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5740640_Extend_Index_c_invoice_uc_externalId_org.sql
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v1/payment/JsonPaymentService.java
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/invoice/review/JsonInvoiceReviewService.java
  backend/de.metas.business.rest-api/src/main/java/de/metas/rest_api/v2/invoice/JsonInvoiceReviewUpsertItem.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/invoice/invoiceReview.feature
  backend/de.metas.util/src/main/java/de/metas/util/Check.java
  misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/SwaggerDocConstants.java
  misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/invoice/JsonInvoicePaymentCreateRequest.java
  misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/common/rest_api/v2/invoice/JsonPaymentAllocationLine.java
Labels: porting-branch

#19466 Soft panda uat desadv shipmentno
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5685650_sys_gh15154_EDI_Desadv_ShipmentDocumentNo.sql
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5685700_sys_gh15154_update_export_format_EDI_Exp_Desadv.sql
  misc/services/camel/de-metas-camel-edi/src/main/xsd/metasfresh/schema.xsd
Labels: ops:without_review_approval, ops:auto_merge_commit

#19460 Merge to master from origin/big_coconut_uat
  backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_xversion/src/main/java/de/metas/vertical/healthcare_ch/forum_datenaustausch_ch/invoice_xversion/request/model/XmlRequest.java
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit
