Repository metasfresh/metasfresh, pull requests merged in 2025-05, with the labels that each got.

#20804 Merge intensive_care_hotfix -> new_dawn_uat 20250512
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/model/validator/M_InOut.java
Labels: ops:without_review_approval, ops:auto_merge_commit

#20810 Be lenient if a definitve invoice has no C_Flatrate_Term_ID
  backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/log/ModularContractLogService.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#20836 FileUtil: store data to `.part` file and then rename that to the actual target file
  misc/de-metas-common/de-metas-common-util/src/main/java/de/metas/common/util/FileUtil.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#20841 Improve WhereClauses for DESADV-Exp-Formats
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/process/Export.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/process/rpl/exp/ExportHelper.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/13-org.adempiere.process.rpl/5755199_sys_Exp_Forma_WhereClause_IsActive.sql
  backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
  backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvBL.java
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5755195_sys_22804_EDI_Desadv_Exp_whereClause_ColumnSize.sql
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5755200_sys_22804_EDI_Desadv_Exp_whereClauses.sql
Labels: ops:without_review_approval, ops:auto_squash_merge

#20854 Merge to new_dawn_uat from origin/soft_panda_hotfix
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/process/Export.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/process/rpl/exp/ExportHelper.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/13-org.adempiere.process.rpl/5755199_sys_Exp_Forma_WhereClause_IsActive.sql
  backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
  backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvBL.java
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5755195_sys_22804_EDI_Desadv_Exp_whereClause_ColumnSize.sql
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5755200_sys_22804_EDI_Desadv_Exp_whereClauses.sql
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#20859 fix flaky unit-test
  backend/de.metas.business.rest-api-impl/src/test/java/de/metas/rest_api/remittanceadvice/CreateRemittanceAdviceServiceTest.java
  backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositeRepository.java
  backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/main/java/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/xml_to_olcands/XmlToOLCandsService.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#20867 merge new_dawn_uat <- vampire_textbook_hotfix
  backend/de.metas.shipper.gateway.dhl/pom.xml
  backend/de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlAddressMapper.java
  backend/de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlConstants.java
  backend/de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlShipperGatewayClient.java
  backend/de.metas.shipper.gateway.dhl/src/test/java/de/metas/shipper/gateway/dhl/DhlAddressMapperTest.java
  backend/de.metas.util/src/main/java/de/metas/util/StringUtils.java
Labels: ops:without_review_approval, ops:auto_merge_commit

#20884 DB-function jsonb_to_xml_fn to convert json to XML
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/jsonb_to_xml_fn.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5756190_sys_jsonb_to_xml_fn.sql
Labels: ops:without_review_approval, ops:auto_squash_merge
