Repository metasfresh/metasfresh, pull requests merged in 2025-01, with the labels that each got.

#19710 Merge to soft_panda_uat from origin/soft_panda_hotfix
  backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#19711 Merge to master from origin/soft_panda_uat
  backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/AbstractInvoiceBL.java
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#19713 Merge to new_dawn_uat from origin/intensive_care_uat
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5734590_sys_AD_User_CC.sql
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/externalsystem/ExternalSystem_Config_StepDef.java
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/workflow/workflowRestController.feature
  backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/I_ExternalSystem_Config_LeichMehl.java
  backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/X_ExternalSystem_Config_LeichMehl.java
  backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/leichmehl/ExportPPOrderToLeichMehlService.java
  misc/dev-support/http-requests/available_processes.http
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-leichundmehl/src/main/java/de/metas/camel/externalsystems/leichundmehl/to_leichundmehl/pporder/ExportPPOrderRouteContext.java
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-leichundmehl/src/test/java/de/metas/camel/externalsystems/leichundmehl/to_leichundmehl/pporder/LeichUndMehlExportPPOrderRouteBuilderTest.java
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-leichundmehl/src/test/resources/de/metas/camel/externalsystems/leichundmehl/to_leichundmehl/pporder/customQueryProcess/30_DispatchMessageRequest.json
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#19677 added dateAcct back into EDI_Cctop_INVOIC_v
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5738460_sys_gh19276_EDI_Cctop_INVOIC_v_DateAcct.sql
Labels: ops:auto_squash_merge

#19685 PLU correction
  misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-leichundmehl/src/main/java/de/metas/camel/externalsystems/leichundmehl/to_leichundmehl/pporder/processor/file/FileUpdater.java
Labels: ops:auto_squash_merge

#19810 change camel-EDI to use the v2-API when sending REMADVs
  misc/services/camel/de-metas-camel-edi/src/main/java/de/metas/edi/esb/remadvimport/ecosio/EcosioRemadvConstants.java
  misc/services/camel/de-metas-camel-edi/src/main/resources/application.properties
Labels: ops:without_review_approval, ops:auto_squash_merge

#19833 Allow returning "_Override_Value_ID" if requested
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/wrapper/AbstractInterfaceWrapperHelper.java
  backend/de.metas.adempiere.adempiere/base/src/test/java/org/adempiere/ad/wrapper/AbstractInterfaceWrapperHelperTest.java
  backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5743930_cli_recompute_ICs_with_Bill_Location_Override_Value_ID.sql
Labels: ops:without_review_approval, ops:auto_squash_merge

#19887 Add optional language parameter to `report.TaxNote` and `report.TextSnippet` functions (#19078)
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/TaxNote.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/TextSnippet.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/taxnote.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/textsnippet.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5736460_sys_gh19076_TextSnippet.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5736470_sys_gh19076_TaxNote.sql
Labels: ops:without_review_approval, ops:auto_squash_merge

#19914 Fix 3 legacy places where C_Invoice_Candidate override location was ignored
  backend/de.metas.business/src/test/java/de/metas/business/BusinessTestHelper.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/agg/key/impl/ICHeaderAggregationKeyBuilder_OLD.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/agg/key/impl/ICLineAggregationKeyBuilder_OLD.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/ExternallyReferencedCandidateRepository.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/TestUpdatedLocationAndUser.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#19944 Fix 3 legacy places where C_Invoice_Candidate override location was ignored (#19914)
  backend/de.metas.business/src/test/java/de/metas/business/BusinessTestHelper.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/agg/key/impl/ICHeaderAggregationKeyBuilder_OLD.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/agg/key/impl/ICLineAggregationKeyBuilder_OLD.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/externallyreferenced/ExternallyReferencedCandidateRepository.java
  backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/api/impl/aggregationEngine/TestUpdatedLocationAndUser.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#19956 introduced and used: M_HU_PI_Item_Product.IsOrderInTuUomWhenMatched
  backend/de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/I_M_HU_PI_Item_Product.java
  backend/de.metas.handlingunits.base/src/main/java-gen/de/metas/handlingunits/model/X_M_HU_PI_Item_Product.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/HUPIItemProduct.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUPIItemProductDAO.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/ordercandidate/spi/impl/OLCandPIIPPriceValidator.java
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5745170_sys_introduced_IsOrderInTuUomWhenMatched.sql
  backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/ordercandidate/spi/impl/OLCandPIIPValidatorTest.java
  backend/de.metas.handlingunits.base/src/test/resources/de/metas/handlingunits/picking/job/repository/PickingJobRepositoryTest.snap
Labels: ops:auto_squash_merge
