Repository metasfresh/metasfresh, pull requests merged in 2025-06, with the labels that each got.

#20923 Cast C_Order.DatePromised to Date for the invoice candidate.
  backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5757000_sys_23657_C_Invoice_Candidate_DatePromised.sql
Labels: ops:without_review_approval, ops:auto_squash_merge

#20924 Merge to new_dawn_uat from origin/soft_panda_hotfix
  backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/47-de.metas.invoicecandidate/5757000_sys_23657_C_Invoice_Candidate_DatePromised.sql
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#20967 mobile HU Consolidation: print label
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/report/labels/HULabelPrintCommand.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/report/labels/HULabelPrintRequest.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/report/labels/HULabelService.java
  backend/de.metas.hu_consolidation.mobile/src/main/java/de/metas/hu_consolidation/mobile/HUConsolidationApplication.java
  backend/de.metas.hu_consolidation.mobile/src/main/java/de/metas/hu_consolidation/mobile/job/HUConsolidationJobService.java
  backend/de.metas.hu_consolidation.mobile/src/main/java/de/metas/hu_consolidation/mobile/job/HUConsolidationLabelPrinter.java
  backend/de.metas.hu_consolidation.mobile/src/main/java/de/metas/hu_consolidation/mobile/job/HUConsolidationTarget.java
  backend/de.metas.hu_consolidation.mobile/src/main/java/de/metas/hu_consolidation/mobile/job/HUConsolidationTargetCloser.java
  backend/de.metas.hu_consolidation.mobile/src/main/java/de/metas/hu_consolidation/mobile/rest_api/HUConsolidationRestController.java
  backend/de.metas.hu_consolidation.mobile/src/main/java/de/metas/hu_consolidation/mobile/rest_api/json/JsonHUConsolidationTarget.java
  misc/services/mobile-webui/mobile-webui-frontend-testing/tests/spec/hu_consolidation/hu_consolidation.spec.js
  misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/huConsolidation/HUConsolidationJobScreen.js
  misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/huConsolidation/SelectHUConsolidationTargetScreen.js
  misc/services/mobile-webui/mobile-webui-frontend/src/apps/huConsolidation/actions/useCurrentTarget.js
  misc/services/mobile-webui/mobile-webui-frontend/src/apps/huConsolidation/actions/usePickingSlot.js
  misc/services/mobile-webui/mobile-webui-frontend/src/apps/huConsolidation/activities/PickingSlotScreen.jsx
  misc/services/mobile-webui/mobile-webui-frontend/src/apps/huConsolidation/activities/SelectHUConsolidationTargetScreen.jsx
  misc/services/mobile-webui/mobile-webui-frontend/src/apps/huConsolidation/api.js
  misc/services/mobile-webui/mobile-webui-frontend/src/apps/huConsolidation/i18n/de.json
  misc/services/mobile-webui/mobile-webui-frontend/src/apps/huConsolidation/i18n/en.json
Labels: branch:new_dawn_uat

#20977 Make get_table_id DB function immutable (#20972)
  backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/functions/get_table_id.sql
  backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5758000_sys_gh23796_get_table_id_immutable.sql
Labels: ops:without_review_approval, ops:auto_merge_commit

#20978 Make get_table_id DB function immutable (#20972)
  backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/ddl/functions/get_table_id.sql
  backend/de.metas.swat/de.metas.swat.base/src/main/sql/postgresql/system/40-sw01_swat/5758000_sys_gh23796_get_table_id_immutable.sql
Labels: ops:without_review_approval, ops:auto_merge_commit
