Repository metasfresh/metasfresh, pull requests merged in 2025-04, with the labels that each got.

#20507 Added & adjusted missing cucumbers commented out in master previously
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/commissioncontracts/hierarchyCommissionAndLicenseFeeCommissionContracts.feature
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/compensationGroup.feature
Labels: branch:new_dawn_uat

#20521 Playwright test push afterdb image
  .github/workflows/cicd.yaml
Labels: ops:without_review_approval, ops:auto_squash_merge

#20541 CICD Workflow: Switching CICD dispatch method
  .github/workflows/cicd.yaml
Labels: ops:auto_squash_merge, branch:new_dawn_uat

#20502 DhlDraftDeliveryOrderCreator needs to create DeliveryPosition because that's what the repo can store
  backend/de.metas.handlingunits.base/src/main/java/de/metas/inoutcandidate/shippertransportation/ShipperDeliveryService.java
  backend/de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlDraftDeliveryOrderCreator.java
  backend/de.metas.shipper.gateway.dhl/src/main/java/de/metas/shipper/gateway/dhl/DhlShipperGatewayClient.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#20560 Fix Rollout Problem related to DESADV DueDate Column Drop on manual created entries
  backend/de.metas.datev/src/main/sql/postgresql/system/5740070_remove_DATEV_DueDate.sql
Labels: ops:auto_squash_merge

#20535 MobileUI Kommissionierung - Show last picked HU BestBeforeDate
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_MobileUI_UserProfile_Picking.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_MobileUI_UserProfile_Picking_Job.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_MobileUI_UserProfile_Picking.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_MobileUI_UserProfile_Picking_Job.java
  backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/mobile_configuration/JsonMobileConfigRequest.java
  backend/de.metas.frontend-testing/src/main/java/de/metas/frontend_testing/masterdata/mobile_configuration/MobileConfigCommand.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/IHUAttributesBL.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/attribute/impl/HUAttributesBL.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/config/mobileui/MobileUIPickingUserProfile.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/config/mobileui/MobileUIPickingUserProfileRepository.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/config/mobileui/PickingJobOptions.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobLine.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobStep.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobStepPickFromMap.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobStepPickedTo.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/model/PickingJobStepPickedToHU.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/repository/PickingJobLoaderAndSaver.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/picking/job/service/commands/PickingJobPickCommand.java
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5751890_sys_add_PickingProfile_ShowLastPickedBestBeforeDate.sql
  backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/picking/job/service/commands/PickingJob_Scenarios_Test.java
  backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/handlingunits/rest_api/JsonHUAttributeConverters.java
  backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/rest_api/json/JsonPickingJobLine.java
  backend/de.metas.picking.rest-api/src/main/java/de/metas/picking/workflow/handlers/activity_handlers/ActualPickingWFActivityHandler.java
  backend/de.metas.workflow.rest-api/src/main/java/de/metas/workflow/rest_api/controller/v2/json/JsonWFProcessHeaderProperties.java
  misc/services/mobile-webui/mobile-webui-frontend-testing/tests/spec/picking/picking_catchWeight.spec.js
  misc/services/mobile-webui/mobile-webui-frontend-testing/tests/utils/screens/picking/PickingJobLineScreen.js
  misc/services/mobile-webui/mobile-webui-frontend/src/containers/activities/picking/PickLineScreen.jsx
Labels: ops:auto_squash_merge

#20593 Update `Weight` fields in `Product` window
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5751970_sys_gh20592_Update_Weight_Fields_Product_Window.sql
Labels: branch:new_dawn_uat

#20640 Fix Rollout on instances with DHL_ShipmentOrder data
  backend/de.metas.shipper.gateway.dhl/src/main/sql/postgresql/system/99-de.metas.shipper.gateway.dhl/5752190_sys_gh20631_Update_DHL_ShipmentOrder.sql
  backend/de.metas.shipper.gateway.dhl/src/main/sql/postgresql/system/99-de.metas.shipper.gateway.dhl/5752195_sys_gh20631_DHL_ShipmentOrder_Drop_column_packageid.sql
Labels: ops:without_review_approval, ops:auto_squash_merge

#20719 Another fix for extraction of Qty and LotNo from HU when creating a DESADV-Pack
  backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/pack/EDIDesadvPackService.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/generichumodel/HU.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/generichumodel/HURepository.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUAssignmentBL.java
  backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/generichumodel/HUTest.java
  backend/de.metas.util/src/main/java/de/metas/util/Check.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#20725 Another fix for extraction of Qty and LotNo from HU when creating a DESADV-Pack (#20719)
  backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/pack/EDIDesadvPackService.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/generichumodel/HU.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/generichumodel/HURepository.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUAssignmentBL.java
  backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/generichumodel/HUTest.java
  backend/de.metas.util/src/main/java/de/metas/util/Check.java
Labels: ops:without_review_approval, ops:auto_merge_commit

#20745 Update `Alternative delivery note 2 summary` report: take out `Merkmale`, `Anzahl` and `Packvorschrift` columns
  backend/metasfresh-dist/base/src/main/jasperreports/de/metas/docs/sales/alternate_inout_2_aggregation/report_details.jrxml
Labels: branch:new_dawn_uat
