Repository metasfresh/metasfresh, pull requests merged in 2025-07, with the labels that each got.

#21037 When creating an AsyncBatch-Workpackage, don't store the C_AsyncBatch_ID thread-locally (#20369)
  backend/de-metas-salesorder/src/main/java/de/metas/salesorder/service/AutoProcessingOrderService.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/wrapper/IInterfaceWrapperHelper.java
  backend/de.metas.async/src/main/java/de/metas/async/AsyncHelper.java
  backend/de.metas.async/src/main/java/de/metas/async/Async_Constants.java
  backend/de.metas.async/src/main/java/de/metas/async/api/IAsyncBatchBL.java
  backend/de.metas.async/src/main/java/de/metas/async/api/IAsyncBatchBuilder.java
  backend/de.metas.async/src/main/java/de/metas/async/api/IWorkPackageQueue.java
  backend/de.metas.async/src/main/java/de/metas/async/api/IWorkpackageProcessorContextFactory.java
  backend/de.metas.async/src/main/java/de/metas/async/api/impl/AsyncBatchBL.java
  backend/de.metas.async/src/main/java/de/metas/async/api/impl/AsyncBatchBuilder.java
  backend/de.metas.async/src/main/java/de/metas/async/api/impl/WorkPackageQueue.java
  backend/de.metas.async/src/main/java/de/metas/async/api/impl/WorkpackageProcessorContextFactory.java
  backend/de.metas.async/src/main/java/de/metas/async/processor/impl/WorkpackageProcessorTask.java
  backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/async/spi/impl/DocOutboundWorkpackageProcessor.java
  backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/async/spi/impl/RecreateArchiveWorkpackageProcessor.java
  backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/impl/DefaultModelArchiver.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/IDunningBL.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/IDunningProducer.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DefaultDunningProducer.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DunningBL.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/process/C_Dunning_Candidate_Process.java
  backend/de.metas.marketing/serialletter/src/main/java/de/metas/letter/process/C_Letter_CreateFrom_MKTG_ContactPerson.java
  backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/dataimporter/ESRImportEnqueuer.java
  backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/IPrintJobBL.java
  backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/impl/PrintJobBL.java
  backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/async/spi/impl/PDFDocPrintingWorkpackageProcessor.java
  backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/model/validator/ConcatenatePDFsCommand.java
  backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/process/C_Invoice_Candidate_EnqueueSelectionForInvoicingAndPDFConcatenating.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/async/C_OLCandToOrderEnqueuer.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/source/OLCandProcessingHelper.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/async/spi/impl/RecreateInvoiceEnqueuer.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/DocumentInterfaceWrapperHelper.java
Labels: ops:without_review_approval, ops:auto_merge_commit

#21035 Port API audit improvements
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_AD_PInstance_Log.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_API_Request_Audit.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_PInstance_Log.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_API_Request_Audit.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/audit/apirequest/ApiAuditLoggable.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/audit/apirequest/request/ApiRequestAudit.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/audit/apirequest/request/ApiRequestAuditRepository.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/audit/data/ExternalSystemParentConfigId.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/IADPInstanceDAO.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessExecutionResult.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessInfoLog.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessInfoLogRequest.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/impl/ADPInstanceDAO.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/ddl/public/functions/getInvoicePaymentAllocations_Report.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5758640_sys_getInvoicePaymentAllocations_Report.sql
  backend/de.metas.business.rest-api-impl/src/main/sql/postgresql/system/50-de.metas.business.rest-api-impl/5638200_sys_gh12966_Improve_Request_Troubleshooting.sql
  backend/de.metas.business.rest-api-impl/src/main/sql/postgresql/system/50-de.metas.business.rest-api-impl/5639250_sys_gh12966_recreate_record_Id_AD_PInstance_Log.sql
  backend/de.metas.util.web/src/main/java/de/metas/util/web/audit/ApiAuditService.java
  backend/de.metas.util.web/src/main/java/de/metas/util/web/exception/RestResponseEntityExceptionHandler.java
  backend/metasfresh-dist/base/src/main/resources/application.properties
Labels: ops:without_review_approval, ops:auto_squash_merge

#21062 Adding `DocStatus` as filter to `C_Invoice`
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5760200_sys_gh24127_C_Invoice_DocStatus.sql
Labels: branch:inner_silence_uat

#21079 Increase org address width
  backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/generics/report_bp_org_block_left.jrxml
Labels: branch:new_dawn_uat

#21144 Add support and a bit of docu on how to use the env-files directly with a bash shell
  backend/de.metas.migration/de.metas.migration.cli/src/main/java/de/metas/migration/cli/workspace_migrate/Main.java
  misc/dev-support/docker/infrastructure/env-files/big_coconut_uat.env
  misc/dev-support/docker/infrastructure/env-files/deep_tundra_uat.env
  misc/dev-support/docker/infrastructure/env-files/default.env
  misc/dev-support/docker/infrastructure/env-files/hard_encoded_uat.env
  misc/dev-support/docker/infrastructure/env-files/inner_silence_uat.env
  misc/dev-support/docker/infrastructure/env-files/intensive_care_uat.env
  misc/dev-support/docker/infrastructure/env-files/iron_plant_uat.env
  misc/dev-support/docker/infrastructure/env-files/master.env
  misc/dev-support/docker/infrastructure/env-files/middle_ages_uat.env
  misc/dev-support/docker/infrastructure/env-files/new_dawn_uat.env
  misc/dev-support/docker/infrastructure/env-files/release.env
  misc/dev-support/docker/infrastructure/env-files/soft_panda_uat.env
  misc/dev-support/docker/infrastructure/env-files/swift_eagle_uat.env
  misc/dev-support/docker/infrastructure/env-files/tasty_ham_uat.env
  misc/dev-support/docker/infrastructure/env-files/tenacious_d_uat.env
  misc/dev-support/docker/infrastructure/env-files/vampire_textbook_uat.env
Labels: ops:without_review_approval, ops:auto_squash_merge
