Repository metasfresh/metasfresh, pull requests merged in 2025-02, with the labels that each got.

#20001 fix trl for IsOrderInTuUomWhenMatched
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5745170_sys_introduced_IsOrderInTuUomWhenMatched.sql
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5745171_sys_IsOrderInTuUomWhenMatched_fixed_trl.sql
Labels: ops:without_review_approval, ops:auto_squash_merge

#20041 unignore the existing cucumber after a quick manual test
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/voidOrder.feature
Labels: ops:without_review_approval, ops:auto_squash_merge

#20062 Trivial improvements done while doing support
  backend/de.metas.edi/src/main/java/de/metas/edi/process/EDI_Desadv_EnqueueForExport.java
  backend/de.metas.edi/src/main/java/de/metas/edi/process/EDI_Desadv_InOut_EnqueueForExport.java
  misc/services/procurement-webui/procurement-webui-backend/src/main/java/de/metas/procurement/webui/rest/MetasfreshSyncRestController.java
  misc/services/procurement-webui/pushReports.http
Labels: ops:without_review_approval, ops:auto_squash_merge

#20066 merging after rollout hard_encoded_uat_21 into hard_encoded_hotfix
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5742970_sys_gh19778_Add_Years_2026_2027_If_Needed.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5742980_sys_gh19778_Periods_For_2026.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5743100_sys_gh19778_Periods_For_2027.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5743330_sys_gh19807_DocType_Window.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_fr_CH.properties
  backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_it_CH.properties
Labels: branch:master

#20075 Minor fixes during support around scales (de.metas.device)
  backend/de.metas.device.adempiere/src/main/java/de/metas/device/accessor/DeviceAccessorsHub.java
  backend/de.metas.device.adempiere/src/main/java/de/metas/device/config/SysConfigDeviceConfigPool.java
  backend/de.metas.device.adempiere/src/main/java/de/metas/device/dummy/DummyDeviceConfigPool.java
  backend/de.metas.util/src/main/java/org/adempiere/util/net/NetUtils.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#20080 `Distribution Order` window update
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5746790_sys_gh20059_DD_Order_Window_Update.sql
Labels: ops:without_review_approval, ops:auto_squash_merge

#20097 provide defaults for newly created mandatory fields
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5746520_AD_BusinessRule_use_AD_Message_ID.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5746522_AD_BusinessRule_default_existing_AD_Message_ID.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5746523_AD_BusinessRule_nonNull_AD_Message_ID.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5746823_businessRule_add_triggering_user_id.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5746824_businessRule_default_triggering_user_id.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5746825_businessRule_nonNull_triggering_user_id.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5747080_reverse_sort_on_business_rule_log_window.sql
Labels: ops:auto_squash_merge

#20119 Enhanced Sales Order doctype transitions cucumber test
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/salesOrder.feature
Labels: ops:auto_squash_merge

#20146 master_int_new_dawn_uat_20250221_2
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/materialDispo/production_and_distribution.feature
  backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DDOrderReference.java
  backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DDOrderReferenceCollector.java
  backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionJob.java
  backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionJobLoader.java
  backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionLauncherCaptionProvider.java
  backend/de.metas.distribution.rest-api/src/main/java/de/metas/distribution/workflows_api/DistributionMobileApplication.java
  backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DDOrderCandidateProcessCommand.java
  backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DDOrderCandidateQuery.java
  backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/DDOrderCandidateRepository.java
  backend/de.metas.manufacturing/src/main/java/de/metas/distribution/ddordercandidate/material_dispo/interceptor/DD_Order_Candidate.java
  backend/de.metas.manufacturing/src/main/java/org/eevolution/model/LiberoValidator.java
  backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Order.java
  backend/de.metas.manufacturing/src/main/java/org/eevolution/model/validator/PP_Order_BOMLine.java
  backend/de.metas.manufacturing/src/main/java/org/eevolution/productioncandidate/model/interceptor/PP_Order_Candidate.java
  backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5747230_sys_gh20125_showDemandDate_in_DDOrderCandidate.sql
  backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5747250_sys_gh20125_showDemandDate_In_DDOrder_And_ADMessage.sql
  backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/handler/ddordercandidate/DDOrderCandidateDeletedHandler.java
  backend/de.metas.material/dispo-service/src/main/java/de/metas/material/dispo/service/event/handler/pporder/PPOrderChangedHandler.java
  backend/de.metas.material/event/src/main/java/de/metas/material/event/MaterialEvent.java
  backend/de.metas.material/event/src/main/java/de/metas/material/event/ddordercandidate/DDOrderCandidateDeletedEvent.java
Labels: ops:without_review_approval, ops:auto_merge_commit

#20145 Fix attributes set in shipment schedule via Rüstliste are overwritten with orderLine attributes
  backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeSetInstanceBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/inoutcandidate/OrderLineShipmentScheduleHandler.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#20174 inner_silence_uat_int_hotfix_inv_activity
  backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_Inventory.java
  backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/FactLineBuilder.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_InventoryLine.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_InventoryLine.java
  backend/de.metas.business/src/main/java/de/metas/inventory/interceptor/M_InventoryLine.java
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5747790_add_C_InventoryLine_C_Activity_ID.sql
Labels: ops:without_review_approval, ops:auto_merge_commit

#20185 master_int_inner_silence_hotfix_20250227
  backend/de.metas.acct.base/src/main/java-legacy/org/compiere/acct/Doc_Inventory.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_M_InventoryLine.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_C_Order.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_M_InventoryLine.java
  backend/de.metas.business/src/main/java/de/metas/inventory/interceptor/M_InventoryLine.java
  backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5747790_add_C_InventoryLine_C_Activity_ID.sql
  backend/de.metas.externalsystem/src/main/java-gen/de/metas/externalsystem/model/X_ExternalSystem_Config_Ebay_Mapping.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java-gen/de/metas/invoicecandidate/model/X_C_Invoice_Candidate.java
Labels: ops:without_review_approval, ops:auto_merge_commit

#20178 fix REMADV-Allocation Bug
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
  backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/AllocationLineCandidateSaver.java
  backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PayableDocument.java
  backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PayableDocumentNotAllocatedException.java
  backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilder.java
  backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationService.java
  backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/remittanceadvice/process/C_RemittanceAdvice_CreateAndAllocatePayment.java
  backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilderTest.java
  backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationServiceTest.java
  backend/de.metas.business/src/main/java/de/metas/allocation/api/C_AllocationLine_Builder.java
  backend/de.metas.business/src/main/java/de/metas/invoice/InvoiceAmtMultiplier.java
  backend/de.metas.business/src/main/java/de/metas/payment/PaymentId.java
  backend/de.metas.business/src/main/java/de/metas/remittanceadvice/RemittanceAdviceLine.java
  backend/de.metas.business/src/main/java/de/metas/remittanceadvice/RemittanceAdviceRepository.java
  backend/de.metas.business/src/test/java/de/metas/remittanceadvice/RemittanceAdviceServiceTest.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#20202 Merge to new_dawn_uat from origin/intensive_care_hotfix
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/compiere/util/TimeUtil.java
  backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/AllocationLineCandidateSaver.java
  backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PayableDocument.java
  backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PayableDocumentNotAllocatedException.java
  backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilder.java
  backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationService.java
  backend/de.metas.banking/de.metas.banking.base/src/main/java/de/metas/banking/remittanceadvice/process/C_RemittanceAdvice_CreateAndAllocatePayment.java
  backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationBuilderTest.java
  backend/de.metas.banking/de.metas.banking.base/src/test/java/de/metas/banking/payment/paymentallocation/service/PaymentAllocationServiceTest.java
  backend/de.metas.business/src/main/java/de/metas/allocation/api/C_AllocationLine_Builder.java
  backend/de.metas.business/src/main/java/de/metas/invoice/InvoiceAmtMultiplier.java
  backend/de.metas.business/src/main/java/de/metas/payment/PaymentId.java
  backend/de.metas.business/src/main/java/de/metas/remittanceadvice/RemittanceAdviceLine.java
  backend/de.metas.business/src/main/java/de/metas/remittanceadvice/RemittanceAdviceRepository.java
  backend/de.metas.business/src/main/java/org/adempiere/mm/attributes/api/impl/AttributeSetInstanceBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/inoutcandidate/OrderLineShipmentScheduleHandler.java
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit
