Repository metasfresh/metasfresh, pull requests merged in 2025-03, with the labels that each got.

#20216 merging `new_dawn_uat`
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5747700_sys_gh20163_Replenishment_Window.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5747770_sys_gh20163_Replenishment_Window.sql
  backend/de.metas.business/src/main/java/de/metas/material/replenish/ReplenishInfo.java
  backend/de.metas.business/src/main/java/de/metas/material/replenish/ReplenishInfoRepository.java
  backend/de.metas.business/src/main/java/de/metas/replenishment/I_M_Material_Needs_Planner_V.java
  backend/de.metas.business/src/main/java/de/metas/replenishment/X_M_Material_Needs_Planner_V.java
  backend/de.metas.business/src/main/sql/postgresql/ddl/views/M_Material_Needs_Planner_V.sql
  backend/de.metas.business/src/main/sql/postgresql/system/43-de.metas.product/5747700_sys_gh20163_M_Material_Needs_Planner_V.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report.jrxml
  backend/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/sales/dunning/report_description.jrxml
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/replenish/process/WEBUI_M_Replenish_Add_Update_Demand.java
  backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5747940_sys_gh20163_M_Replenish_Add_Update_Demand.sql
Labels: ops:without_review_approval, ops:auto_merge_commit

#20230 Fix creation of SSCC18 from a DESADV-Line with UOM TU or COLI, if there is no picked HU
  backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/pack/CreateEDIDesadvPackRequest.java
  backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/pack/EDIDesadvPackRepository.java
  backend/de.metas.edi/src/main/java/de/metas/edi/sscc18/DesadvLineSSCC18Generator.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#20246 make sure the HU's qty we subtract from the inOutLine's qty is compatible with the latter
  backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/production/multipleProductionCandidates.feature
  backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/pack/EDIDesadvPackService.java
  backend/de.metas.edi/src/main/java/de/metas/edi/sscc18/DesadvLineSSCC18Generator.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#20300 master_int_new_dawn_uat_20250307
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_AD_Issue.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-legacy/org/adempiere/exceptions/AdempiereException.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/error/impl/ErrorManager.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/i18n/Msg.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessExecutor.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/ProcessInfo.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/table/api/IADTableDAO.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/exceptions/DBUniqueConstraintException.java
  backend/de.metas.edi/src/main/java/de/metas/edi/process/EDIExportDocOutboundLog.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/qrcodes/ean13/EAN13HUQRCode.java
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5748730_update_valrule_HU_Label_processes.sql
  backend/de.metas.handlingunits.base/src/test/java/de/metas/handlingunits/qrcodes/ean13/EAN13HUQRCodeTest.java
  backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/rest_api/v1/ManufacturingOrderReportProcessCommand.java
  backend/de.metas.manufacturing.rest-api/src/main/java/de/metas/manufacturing/rest_api/v2/ManufacturingOrderReportProcessCommand.java
  backend/de.metas.manufacturing/src/main/java/org/eevolution/process/PP_Product_BOM_Check.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/process/adprocess/ADProcessInstancesRepository.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/process/adprocess/ADProcessParametersRepository.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/DocumentValidStatus.java
  backend/de.metas.util.web/src/main/java/de/metas/rest_api/utils/JsonErrors.java
  backend/de.metas.util.web/src/main/java/de/metas/rest_api/utils/v2/JsonErrors.java
Labels: ops:without_review_approval, ops:auto_merge_commit

#20302 Add views to help diagnose REMADV inconsistencies
  backend/de.metas.edi/src/main/sql/postgresql/ddl/views/de.metas.edi/c_remittanceadvice_diag_I_to_P_allocs_v.sql
  backend/de.metas.edi/src/main/sql/postgresql/ddl/views/de.metas.edi/c_remittanceadvice_diag_I_to_SI_allocs_v.sql
  backend/de.metas.edi/src/main/sql/postgresql/ddl/views/de.metas.edi/c_remittanceadvice_diag_SI_to_I_allocs_v.sql
  backend/de.metas.edi/src/main/sql/postgresql/ddl/views/de.metas.edi/c_remittanceadvice_diag_problems_v.sql
  backend/de.metas.edi/src/main/sql/postgresql/ddl/views/de.metas.edi/c_remittanceadvice_diag_v.sql
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5748780_sys_c_Remittanceadvice_diag_views.sql
Labels: ops:without_review_approval, ops:auto_squash_merge

#20301 Merge to new_dawn_uat from origin/soft_panda_hotfix
  backend/de.metas.edi/src/main/java/de/metas/edi/api/impl/DesadvBL.java
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#20342 forum-datenaustausch - Make sure patients are always created as BPartners
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5749150_sys_C_Invoice_Detail_add_perf_idx.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5749160_sys_AD_PRocess_fix_excel_process_classname.sql
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v1/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
  backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/main/java/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/xml_to_olcands/XmlToOLCandsService.java
  backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/test/java/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/xml_to_olcands/XmlToOLCandsServiceTest.java
  misc/de-metas-common/de-metas-common-ordercandidates/src/main/java/de/metas/common/ordercandidates/v1/response/JsonAttachment.java
  misc/dev-support/docker/infrastructure/env-files/big_coconut_uat.env
  misc/dev-support/idea-runConfigurations/RunCucumberTest - big_coconut_uat.run.xml
Labels: ops:without_review_approval, ops:auto_squash_merge

#20350 Merge to master from origin/big_coconut_uat
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5749150_sys_C_Invoice_Detail_add_perf_idx.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5749160_sys_AD_PRocess_fix_excel_process_classname.sql
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v1/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
  backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/main/java/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/xml_to_olcands/XmlToOLCandsService.java
  backend/vertical-healthcare_ch/forum_datenaustausch_ch.invoice_rest-api/src/test/java/de/metas/vertical/healthcare/forum_datenaustausch_ch/rest/xml_to_olcands/XmlToOLCandsServiceTest.java
  misc/de-metas-common/de-metas-common-ordercandidates/src/main/java/de/metas/common/ordercandidates/v1/response/JsonAttachment.java
  misc/dev-support/idea-runConfigurations/RunCucumberTest - big_coconut_uat.run.xml
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#20391 webui: Don't allow user to navigate out from a document with changes (#20164)
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentSaveStatus.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/Document.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/DocumentSaveStatus.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/sql/SqlDocumentsRepository.java
  backend/de.metas.ui.web.base/src/main/sql/postgresql/system/41-de.metas.ui.web.base/5747490_msg_webui.window.discardChanges.sql
  frontend/package.json
  frontend/src/__tests__/containers/DocList.test.js
  frontend/src/actions/MenuActions.js
  frontend/src/actions/WindowActions.js
  frontend/src/api/window.js
  frontend/src/components/Container.js
  frontend/src/components/app/ChangeCurrentWorkplace.js
  frontend/src/components/app/Indicator.js
  frontend/src/components/app/MasterWindow.js
  frontend/src/components/app/Modal.js
  frontend/src/components/comments/CommentsPanelForm.js
  frontend/src/components/documentReferences/DocumentReferenceGroup.js
  frontend/src/components/documentReferences/DocumentReferenceItem.js
  frontend/src/components/documentReferences/DocumentReferences.js
  frontend/src/components/header/Header.js
  frontend/src/components/header/RedirectHandler.js
  frontend/src/components/header/SubHeader.js
  frontend/src/components/header/UserDropdown.js
  frontend/src/components/header/breadcrumb/Breadcrumb.js
  frontend/src/components/header/main_menu/MenuOverlay.js
  frontend/src/components/header/main_menu/MenuOverlayContainer.js
  frontend/src/components/header/main_menu/MenuOverlayItem.js
  frontend/src/components/inbox/Inbox.js
  frontend/src/components/inbox/InboxItem.js
  frontend/src/constants/ActionTypes.js
  frontend/src/constants/IndicatorState.js
  frontend/src/constants/StaticModalType.js
  frontend/src/containers/DocList.js
  frontend/src/containers/DocumentList.js
  frontend/src/containers/MasterWindowContainer.js
  frontend/src/containers/NavigationTree.js
  frontend/src/reducers/index.js
  frontend/src/reducers/redirect.js
  frontend/src/reducers/windowHandler.js
  frontend/src/routes/KeyRoutes.js
  frontend/src/utils/index.js
  frontend/src/utils/locale.js
Labels: ops:without_review_approval, ops:auto_merge_commit

#20415 Merge to master from origin/new_dawn_uat
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_I_Product.java
  backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/X_I_Product.java
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5749690_ExtednIMportProduct.sql
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v1/bpartner/bpartnercomposite/jsonpersister/JsonPersisterService.java
  backend/de.metas.business/src/main/java/de/metas/bpartner/composite/BPartnerLocationType.java
  backend/de.metas.business/src/main/java/de/metas/pricing/InvoicableQtyBasedOn.java
  backend/de.metas.business/src/main/java/de/metas/product/impexp/CompositeProductImportProcessListener.java
  backend/de.metas.business/src/main/java/de/metas/product/impexp/MProductImportTableSqlUpdater.java
  backend/de.metas.business/src/main/java/de/metas/product/impexp/ProductImportHelper.java
  backend/de.metas.business/src/main/java/de/metas/product/impexp/ProductImportProcess.java
  backend/de.metas.business/src/main/java/de/metas/product/impexp/ProductImportProcessListener.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/IHandlingUnitsDAO.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/CreateTUPackingInstructionsCommand.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/CreateTUPackingInstructionsRequest.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/product/impexp/HUProductImportProcessListener.java
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#20407 fix RecreateInvoiceWorkpackageProcessor DB deadlock (#16997) (#19271)
  backend/de-metas-salesorder/src/main/java/de/metas/salesorder/candidate/AutoProcessingOLCandService.java
  backend/de-metas-salesorder/src/main/java/de/metas/salesorder/service/AutoProcessingOrderService.java
  backend/de.metas.async/src/main/java/de/metas/async/AsyncBatchId.java
  backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/shipping/JsonShipmentService.java
  backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/invoicecandidate/C_Invoice_Candidate_StepDef.java
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/Docs_Sales_TransportOrder_Details.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5746990_sys_gh20089_Docs_Sales_TransportOrder_Details.sql
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/inout/invoicecandidate/M_InOutLine_Handler.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoice/InvoiceService.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/IInvoiceCandBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/api/impl/InvoiceCandBL.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/async/spi/impl/RecreateInvoiceWorkpackageProcessor.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#20425 Minor improvements from support/debug session
  backend/de.metas.acct.base/src/main/java/de/metas/acct/vatcode/impl/VATCodeDAO.java
  backend/de.metas.business/src/main/java/org/eevolution/api/impl/ProductBOMDAO.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/impl/LUTUProducerDestination.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
Labels: ops:without_review_approval, ops:auto_squash_merge

#20426 Merge to new_dawn_uat from origin/intensive_care_hotfix
  backend/de.metas.acct.base/src/main/java/de/metas/acct/vatcode/impl/VATCodeDAO.java
  backend/de.metas.business/src/main/java/org/eevolution/api/impl/ProductBOMDAO.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/impl/LUTUProducerDestination.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#20435 Inner silence uat merge hotfix 24032025
  backend/de.metas.business/src/main/java/de/metas/invoice/interceptor/C_InvoiceLine.java
  backend/de.metas.business/src/main/sql/postgresql/system/43-de.metas.product/5749900_I_C_InvoiceLine_Product_madatoryLogic.sql
Labels: ops:without_review_approval, ops:auto_merge_commit

#20437 Merge to master from origin/new_dawn_uat
  .github/workflows/cicd.yaml
  backend/de.metas.acct.base/src/main/java/de/metas/acct/vatcode/impl/VATCodeDAO.java
  backend/de.metas.business/src/main/java/org/eevolution/api/impl/ProductBOMDAO.java
  backend/de.metas.edi/src/main/sql/postgresql/system/80-de.metas.edi/5749850_sys_gh20419_EXP_Format_Update.sql
  backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5749890_sys_gh20427_Update_HU_Editor_Window.sql
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/allocation/transfer/impl/LUTUProducerDestination.java
  backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HandlingUnitsDAO.java
  docker-builds/Dockerfile.backend.api
  docker-builds/Dockerfile.backend.app
  docker-builds/Dockerfile.camel.edi
  docker-builds/Dockerfile.camel.externalsystems
  docker-builds/mobiletest/.env
  docker-builds/mobiletest/.gitignore
  docker-builds/mobiletest/compose.yml
  docker-builds/mobiletest/default.conf
  docker-builds/mobiletest/metasfresh.properties
  docker-builds/mobiletest/mobile-config.js
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#20442 Update pipeline 0.4.1 remove pr info part not working on merge
  .github/workflows/cicd.yaml
Labels: ops:without_review_approval, ops:auto_squash_merge

#20443 Master merge inner silence uat 25032025
  backend/de.metas.business/src/main/java/de/metas/invoice/interceptor/C_InvoiceLine.java
  backend/de.metas.business/src/main/sql/postgresql/system/43-de.metas.product/5749900_I_C_InvoiceLine_Product_madatoryLogic.sql
Labels: ops:without_review_approval, ops:auto_merge_commit

#20455 Adding test dispatch job to cicd workflow
  .github/workflows/cicd.yaml
Labels: ops:auto_squash_merge

#20463 new_dawn_uat_int_intensive_care_hotfix_20250326
  backend/de-metas-salesorder/src/main/java/de/metas/salesorder/service/AutoProcessingOrderService.java
  backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/wrapper/IInterfaceWrapperHelper.java
  backend/de.metas.adempiere.adempiere/base/src/test/java/de/metas/impexp/format/ImpFormatColumnTest.java
  backend/de.metas.async/src/main/java/de/metas/async/AsyncHelper.java
  backend/de.metas.async/src/main/java/de/metas/async/Async_Constants.java
  backend/de.metas.async/src/main/java/de/metas/async/api/IAsyncBatchBL.java
  backend/de.metas.async/src/main/java/de/metas/async/api/IAsyncBatchBuilder.java
  backend/de.metas.async/src/main/java/de/metas/async/api/IWorkPackageQueue.java
  backend/de.metas.async/src/main/java/de/metas/async/api/IWorkpackageProcessorContextFactory.java
  backend/de.metas.async/src/main/java/de/metas/async/api/impl/AsyncBatchBL.java
  backend/de.metas.async/src/main/java/de/metas/async/api/impl/AsyncBatchBuilder.java
  backend/de.metas.async/src/main/java/de/metas/async/api/impl/WorkPackageQueue.java
  backend/de.metas.async/src/main/java/de/metas/async/api/impl/WorkpackageProcessorContextFactory.java
  backend/de.metas.async/src/main/java/de/metas/async/processor/impl/WorkpackageProcessorTask.java
  backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/async/spi/impl/DocOutboundWorkpackageProcessor.java
  backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/async/spi/impl/RecreateArchiveWorkpackageProcessor.java
  backend/de.metas.document.archive/de.metas.document.archive.base/src/main/java/de/metas/document/archive/spi/impl/DefaultModelArchiver.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/IDunningBL.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/IDunningProducer.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DefaultDunningProducer.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/api/impl/DunningBL.java
  backend/de.metas.dunning/src/main/java/de/metas/dunning/process/C_Dunning_Candidate_Process.java
  backend/de.metas.marketing/serialletter/src/main/java/de/metas/letter/process/C_Letter_CreateFrom_MKTG_ContactPerson.java
  backend/de.metas.payment.esr/src/main/java/de/metas/payment/esr/dataimporter/ESRImportEnqueuer.java
  backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/IPrintJobBL.java
  backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/api/impl/PrintJobBL.java
  backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/async/spi/impl/PDFDocPrintingWorkpackageProcessor.java
  backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/model/validator/ConcatenatePDFsCommand.java
  backend/de.metas.printing/de.metas.printing.base/src/main/java/de/metas/printing/process/C_Invoice_Candidate_EnqueueSelectionForInvoicingAndPDFConcatenating.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/async/C_OLCandToOrderEnqueuer.java
  backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/api/source/OLCandProcessingHelper.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/async/spi/impl/RecreateInvoiceEnqueuer.java
  backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/order/invoicecandidate/C_OrderLine_Handler.java
  backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/model/DocumentInterfaceWrapperHelper.java
Labels: ops:without_review_approval, ops:auto_merge_commit

#20462 Merge to master from origin/new_dawn_uat
  backend/de.metas.manufacturing/src/main/sql/postgresql/system/30-de.metas.adempiere.libero/5749930_Produktionsdisposition_ResourceAttributes.sql
  misc/services/camel/de-metas-camel-edi/misc/pseudonomize_metasfresh-inhouse-edi-xmls.py
Labels: ops:without_review_approval, porting-branch, ops:auto_merge_commit

#20471 Add dedicated metasfresh-Support AD_User that could be notified via mail is a scheduled task failed
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5744090_sys_gh19856_AD_SysConfig_Scheduler_notifyOnNotOK_to_Y.sql
  backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5744120_cli_gh19856_add_support_user.sql
  backend/de.metas.handlingunits.base/src/main/sql/postgresql/system/5744050_cli_gh19856_MD_Stock_Update_From_M_HUs_AD_Scheduler_AD_Client_ID.sql
Labels: ops:without_review_approval, ops:auto_squash_merge
